- plugin.json
- server/manifest.go
> Revert plugin id back to jira

- plugin.json
- server/manifest.go
Since v1.0.3 is broken we should get this out rather soon.
> Release 1.0.4

- server/plugin.go
- server/plugin_test.go
- server/webhook.go
This PR improves the error handling by not longer returning 200 for 
invalid JSON requests.
It also rewrites the code to use idiomatic error handling.
It adds logging for all http requests.
Fixes #3 
Fixes #17
> Improve error handling and logging

- .circleci/config.yml
Adding a functionality to deploy to GH when we tag a release
> deploy to GH when tag a release

- server/command.go
- server/issue.go
https://mattermost.atlassian.net/browse/MM-15101
- Ticket didn't specify how exactly to match the text entered with the transition. Method implemented is a case-insensitive `strings.Contains()` on the transition target state name.
> MM-15101 Adding /jira transition

- server/command.go
The install instructions for server were giving the wrong URL.
> * give correct URL in /jira install server instructions

- server/command.go
@jasonblais please verify that I merged your changes in #77 correctly.
1. Fix typo (Disonnect > Disconnect)
2. Consistency in terms of first-person vs third-person terms, e.g. `Change` , `Changes`
3. Consistency with capitalization
4. Update "server Jira instance" to "Jira Server or Data Center instance"
5. Update "cloud Jira instance" to "Jira Cloud instance"
> Minor modifications to "/jira help" text (#77)

- server/templates/ac/user_disconnected.html
@asaadmahmood this is a clean back-merge from 2.0 to master, FYI.
> Update user_disconnected.html (#76)

- webapp/src/components/jira_field.jsx
- webapp/src/components/jira_fields.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
**Summary**
This PR addresses the issue when a user tries to select a priority field when creating a ticket.  
The priority field type, inside the fields object, is an object, not a string.  This requires handling priority differently to satisfy the embedded priority struct inside the IssueFields struct.
For the priority ReactSelectSetting component, filter against
this.props.value.id to get the value, not this.props.value which is an
object
Below is the working case which appropriately selects the priority field.
An example of a ticket created with the priority field set can be viewed [Here](https://mmtest.atlassian.net/browse/EXT-128)
https://mattermost.atlassian.net/browse/MM-15536
> [MM-15589] Create Issue: (Jira server) Priority field fails to select

- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
- webapp/src/components/react_select_setting.jsx
> MM-15733 - Making react select theme compatible

- server/issue.go
@cpoile _almost_ a clean merge, please double-check
> [MM-15862] detect if the post is a reply ...(#94)

- webapp/src/components/jira_fields.jsx
This PR is to allow all Jira Fields to show up in the create issue dialog window.  This will be used to test the determine which fields currently work.
> Allow all Jira Fields to show up in create-issue dialog

- webapp/src/components/input.jsx
- webapp/src/components/jira_field.jsx
@cpoile The 3rd file/change was redundant in master
* [MM-15658] fix for description not editable on server instances
* cleanup
> [MM-15658] Fix for description not editable on server instances (#95)

- webapp/src/components/jira_field.jsx
- webapp/src/components/jira_fields.jsx
- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
- webapp/src/components/react_select_setting.jsx
fixed MM-15733. 
- Problem was the theme was not being passed to ReactSelectSettings that were created in jira_field.
- Made theme a required prop to provide warning in the future. 
- Also added a null check on the theme before trying to style using it. Just in case -- so we'll get no theme, instead of crashing the app.
#78
> Mm 15733 fix to theme pr

- server/command.go
- server/user.go
As described in the ticket below, improve the `/jira disconnect` user experience.
[MM-15286](https://mattermost.atlassian.net/browse/MM-15286)
> [MM-15286] Improve the /jira disconnect user experience

- server/instance_cloud.go
- server/instance_server.go
- server/kv.go
- server/user_cloud.go
- server/user_server.go
- Prevents multiple sanctimonious valid connect links.
- Prevents am SSRF in the jira server connect flow. 
- Based on and replaces: https://github.com/mattermost/mattermost-plugin-jira/pull/96
> MM-15900 Improving connection flows.

- server/user.go
https://mattermost.atlassian.net/browse/MM-15952
> MM-15952 Fixed GetUserInfo API incorrectly handling the "disconnected" state

- server/command.go
- server/http.go
- server/plugin.go
- server/utils.go
- server/webhook.go
- Fixed https://mattermost.atlassian.net/browse/MM-15880
- Also removed dead code (was tangentially related)
@asaadmahmood I ended up taking the PNG icon because the SVG was huge (125Kb?)
> [MM-15880] Replaced the S3 icon used for command ephemeral posts

- webapp/src/components/jira_field.jsx
- webapp/src/components/jira_fields.jsx
- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
- webapp/src/components/react_select_setting.jsx
cc @cpoile 
* recommitting: "MM-15733 - Making react select theme compatible (#78)"
* fix - theme won't crash, and theme now applies to all select settings
> Mm 15733 fix to theme pr (#104)

- server/command.go
- server/user.go
cc @cpoile 
* [MM-15286] Improve the /jira disconnect user experience
* fixup
> [MM-15286] Improve the /jira disconnect user experience (#101)

- .gitignore
- server/http.go
- server/issue.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/form_button.jsx
- webapp/src/components/jira_issue_selector/index.js
- webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/modals/attach_comment_to_issue/index.js
@cpoile please verify
* [MM-15677] autocomplete for issue keys in Attach to Jira Issue
* redesign, PM & UX comments
* modal size
* passing in theme
* cleanup
* cleanup
* PR comments, and improving the search experience by trimming
> [MM-15677] autocomplete for issue keys in Attach to Jira Issue (#79)

- server/instance_cloud.go
- server/instance_server.go
- server/kv.go
- server/user_cloud.go
- server/user_server.go
@crspeller please review: there were numerous if obvious conflicts during the back-merge.
@cpoile FYI
> Improving connection flows. (#110)

- webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/react_select_setting.jsx
- webapp/src/components/utils.jsx
* MM-15922 - Fixing theme and dropdown issue
* refactored theme styling, reduced duplication
* Updating theme
* Updating code
* Updating react select settings
> MM-15922 - Fixing theme and dropdown issue (#111)

- server/issue.go
**Summary**
This PR reformats the message, in Jira, that links back to the MM post which was used to create the ticket. 
New images: 
Message with no additional description text.
Message with additional description text.
https://mattermost.atlassian.net/browse/MM-15906
> [MM-15906] Update issue description created via Mattermost-Jira plugin

- server/kv.go
- server/plugin.go
The default TTL is set to 1s.
Ticket: https://mattermost.atlassian.net/browse/MM-15249
> MM-15249: cache the current Jira instance

- webapp/src/components/jira_field.jsx
- webapp/src/components/react_select_setting.jsx
Enable users to cancel their selection in select-choice dropdown fields.
Looks like this:
[MM-15936](https://mattermost.atlassian.net/browse/MM-15936)
> [MM-15936] Enable users to cancel their selection in select-choice dropdown fields

- webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
- webapp/src/components/react_select_setting.jsx
https://mattermost.atlassian.net/browse/MM-15983
> MM-15983 - Updating dropdown issue

- server/command.go
- server/utils.go
- server/utils_test.go
https://mattermost.atlassian.net/browse/MM-15930
> Fixed MM-15930: canonicalize Jira URL in install

- server/user_cloud.go
https://mattermost.atlassian.net/browse/MM-15968
> MM-15968 Better error message on missing cookies

- README.md
This is the final PR for Jira 2.0 documentation.
Devs: Please help do a high-level review, focused on technical correctness. Feedback on areas that could be improved or clarified is welcome.
Katie: Please help with PM review, particularly for the Configuration section. Instructions for Jira Cloud and Jira Server/Data Center are 90% the same, but I'd want to ensure it is clear where differences exist.
Amy: Please help with Editor review.
> Jira 2.0 Docs

- go.mod
- go.sum
- server/issue.go
- webapp/src/components/modals/create_issue/create_issue.jsx
Ticket: https://mattermost.atlassian.net/browse/MM-16266
Also updated to go-jira 1.7 that supports `Reporter`
> MM-16266: always add Reporter creating issues on Jira Server

- webapp/src/components/jira_field.jsx
- webapp/src/components/react_select_setting.jsx
- essentially I was trying to compare objects, which doesn't work.  (facepalm)
Fixes: [MM-16308](https://mattermost.atlassian.net/browse/MM-16308)
> [MM-16308] Single Select validation issue

- README.md
In preparation for this week's release
> Migrate README updates from jira2 to master branch

- server/command.go
- Check if there is an instance installed before creating a connect link
- PM review for the returned message
- Fixes: [MM-16124](https://mattermost.atlassian.net/browse/MM-16124)
> [MM-16124] Jira Connect slash command will generate a link when no instance is installed

- server/issue.go
- webapp/src/components/jira_field.jsx
- webapp/src/components/jira_fields.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
Included https://github.com/mattermost/mattermost-plugin-jira/pull/182 here to pass the tests, it should be merged first
> Cherry-pick PR #151

- webapp/src/components/jira_field.jsx
Awaiting https://github.com/mattermost/mattermost-plugin-jira/pull/186
> Cherrypick #158:  Fix serching in single select dropdowns.

- server/testdata/webhook-issue-updated-assigned-on-server.json
- server/webhook_http_test.go
- server/webhook_parser.go
- Fixes a bug where we were returning a 500 error in response to a webhook from Jira Server after changing the assignee of an issue.
- [MM-16635](https://mattermost.atlassian.net/browse/MM-16635)
> [MM-16625] jira server sends issue_updated for a assignee change

- server/issue.go
- webapp/src/components/modals/create_issue/create_issue.jsx
- Send the key and the localized name to the server (for fields we don't support)
- Check against the key (which shouldn't change). Give feedback with the localized name.
- [MM-16503](https://mattermost.atlassian.net/browse/MM-16503)
> [MM-16503] Special handling of Reporter is broken in localized Jira

- server/testdata/webhook-comment-created-server.json
- server/webhook_http_test.go
- server/webhook_parser.go
- Fixes a bug where we were returning a 500 error in response to a webhook from Jira Server after commenting on an issue.
- Fixes [MM-16680](https://mattermost.atlassian.net/browse/MM-16680)
> [MM-16680] Webhook issue comments broken on server

- server/command.go
- server/issue.go
- server/kv.go
ticket: https://mattermost.atlassian.net/browse/MM-16438
- Fixed parameter validation
- Improved transition disambiguation
- Also fixed a bug in a prior commit for unmarshalling ASC
> MM-16438: fixed and slightly improved `/jira transition`

- server/webhook.go
- server/webhook_parser.go
- Checking for view issue permissions.
- Unless it's a comment, then check for permissions to view the comment.
[MM-16688](https://mattermost.atlassian.net/browse/MM-16688)
> [MM-16688] Make DMs permissions aware

- server/command.go
- server/user.go
Ticket: https://mattermost.atlassian.net/browse/MM-16864
> MM-16864: added /jira info command

- server/command.go
Ticket: https://mattermost.atlassian.net/browse/MM-17000
cc @jasonblais
> MM-17000: redirect from /jira install, no need to display the link

- server/instance.go
- server/kv.go
- server/subscribe.go
- server/user.go
- server/user_cloud.go
- server/user_server.go
Ticket: https://mattermost.atlassian.net/browse/MM-16870
> MM-16870: Added PluginVersion to User, Instance, and Subscriptions KV

- server/command.go
- server/issue.go
Ticket: https://mattermost.atlassian.net/browse/MM-16540
Also effectively cleaned up the handling of closing resp.Body, no need for https://github.com/mattermost/mattermost-plugin-jira/pull/215
> MM-16540: userFriendlyJiraError

- webapp/src/components/setup_ui/setup_ui.jsx
- fixed text (and a semicolon)
[MM-16950](https://mattermost.atlassian.net/browse/MM-16950)
> MM-16950: `JIRA` in tooltip of channel header icon should say `Jira`

- server/command.go
- server/instance_cloud.go
- server/instance_server.go
- server/issue.go
- server/kv.go
- server/user.go
- server/webhook_parser.go
@cpoile made it work, but not quite the same way as it was done in 2.0.
@jasonblais this should also fix your issues with levbrouk.atlassian.net if I understand them correctly.
This time it is a little less hacky and should not require disconnecting/re-connecting as far as I can tell.
> Updated AccountId handling to match jira2

- webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
This PR fixes a variable typo in the `channel_settings_internal.jsx` component
https://mattermost.atlassian.net/browse/MM-16887
> [MM-16887] Variable name typo fix

- server/http_test.go
- server/instance.go
- server/instance_cloud.go
- server/instance_server.go
- server/kv_mock_test.go
- server/subscribe.go
Various conflicts with my pr and others.
> Fixing conflicts.

- webapp/src/utils/jira_issue_metadata.jsx
This PR fixes an issue with using the channel subscriptions feature on Jira Server. An error is occurring when parsing the custom fields of a given project.
https://mattermost.atlassian.net/browse/MM-17108
https://mattermost-plugin-jira-test.test.spinmint.com
> [MM-17108] Correctly support custom fields correct for cloud and server

- plugin.json
- server/http_test.go
- server/subscribe.go
- server/subscribe_test.go
- Also requires 5.12 for this and for other features already in use.
> MM-17235, MM-17075 Moving to using KVCompareAndSet

- webapp/src/components/form_button.jsx
- webapp/src/components/input.jsx
- webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
- webapp/src/components/modals/create_issue/create_issue.jsx
- webapp/src/utils/styles.js
Ticket: https://mattermost.atlassian.net/browse/MM-15908
Should also fix: https://mattermost.atlassian.net/browse/MM-17136
**Before:**
**After:**
- Fixes the styling (spacing, background, etc for the labels).
- Adjusts the x icon both in the labels and the fields.
- Adjusts the padding of the modal.
- Makes the error appear left aligned with the inputs.
- Moves Delete button to the left.
- Also fixes the disabled state for the Set Subscription button.
> MM-15908 - Updating Jira UX

- webapp/src/components/setup_ui/setup_ui.jsx
- webapp/src/plugin.jsx
- Only need to register/unregister in the component update fn
- Refactored a bit; felt weird to call in an un-exported fn
- Fixes [MM-17041](https://mattermost.atlassian.net/browse/MM-17041)
> [MM-17041] multiple 'Jira' icons in channel header

- server/issue.go
- Looks like a merge error
- Fixes [MM-17380](https://mattermost.atlassian.net/browse/MM-17380)
> [MM-17380] Intermittent 500 errors when using create

- server/webhook_http.go
cc @cpoile - his code, @jasonblais FYI
> MM-17480: removed DM notifications from legacy webhooks

- plugin.json
As per MM-17252: https://mattermost.atlassian.net/browse/MM-17252
> Updated Webhook URL params to be a Mega Webhook

- webapp/src/utils/styles.js
> MM-17524 - Updating theme styles for jira

- server/webhook_parser.go
Users have reported the error `Unsupported webhook data: jira:issue_updated` that provides little to no context as to why the error occurred. This PR makes it so the logged/returned error includes the fields that were rejected to provide some context.
https://mattermost.atlassian.net/browse/MM-17682
> [MM-17682] Improve error logging when issue updated event has no supported fields

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
https://mattermost.atlassian.net/browse/MM-18202
> Bump version to 2.1.1 for patch release

- README.md
- Updated user connections area
- Added info to troubleshooting about more verbose logging mode
> Add info to troubleshooting area

- README.md
> Added note to troubleshooting

- server/webhook_parser.go
This is a re-try of https://github.com/mattermost/mattermost-plugin-jira/pull/302 - had a little git issue merging, seemed cleaner to cut a new PR with the cherry-picks.
https://mattermost.atlassian.net/browse/MM-17872
> MM-17872: display different headline in comment created/updated

- build/manifest/main.go
- server/client.go
- server/issue.go
- also fixed build/manifest to generate a manifest.ts, not manifest.js
Fixes https://mattermost.atlassian.net/browse/MM-17613
> MM-17613: Fixed error message in Cloud SearchIssues

- server/issue.go
Fixes https://mattermost.atlassian.net/browse/MM-18725
> Fixed MM-18725: failure to create reply posts in threads

- plugin.json
- server/manifest.go
- webapp/src/manifest.ts
To be merged once the outstanding PRs are merged,
- https://github.com/mattermost/mattermost-plugin-jira/pull/323
- https://github.com/mattermost/mattermost-plugin-jira/pull/324
- ~~https://github.com/mattermost/mattermost-plugin-jira/pull/325~~
> Bumped release number to 2.2

- go.sum
- server/issue.go
- webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
Re-implemented, server-side.
Fixes https://mattermost.atlassian.net/browse/MM-18154
> Fixed MM-18154: attach also searches for issue key

- go.sum
- plugin.json
- server/manifest.go
- webapp/src/manifest.ts
Awaiting https://github.com/mattermost/mattermost-plugin-jira/pull/343 which is in testing/debugging
> Bumped plugin version to v2.2.2

- server/command.go
- server/command_test.go
- server/user.go
- server/user_test.go
**Summary**
This PR introduces support for filtering on field values for channel subscriptions.
[https://mattermost.atlassian.net/browse/MM-18080](https://mattermost.atlassian.net/browse/MM-18080)
**Additional info**
Closes #315
> [MM-19179] Show user their settings with `/jira settings`

- webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
This PR adds descriptions under each of the options for the inclusion field of channel subscriptions.
https://mattermost.atlassian.net/browse/MM-19072
> [MM-19072] Add sub caption to channel subscription inclusion field

- server/issue.go
- server/subscribe_test.go
- server/testdata/webhook-cloud-issue-created-many-fields.json
- webapp/src/components/react_select_setting.jsx
This PR makes it so the user can enter labels in the subscription filters.
https://mattermost.atlassian.net/browse/MM-19073
The issue with labels is that Jira's API does not allow us to fetch them. So the user has to enter the labels in themselves, hopefully spelling them correctly. This is something that could go in our docs.
> [MM-19073] Make labels and custom labels work correctly with subscriptions

- webapp/src/components/confirm_modal.tsx
- webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
- webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap
- webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
- webapp/src/components/modals/channel_settings/channel_settings_filters.tsx
- webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
- webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
- webapp/src/components/react_select_setting.jsx
This PR fixes some accessibility issues regarding the enter button. Making all of the buttons in the modal require focus in order for the enter button to trigger the button click.
https://mattermost.atlassian.net/browse/MM-19791
> [MM-19791] Fix issues with enter button deleting filter rows

- webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_filter.test.tsx.snap
- webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_filters.test.tsx.snap
- webapp/src/components/modals/channel_settings/channel_settings_filter.test.tsx
- webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
- webapp/src/components/modals/channel_settings/channel_settings_filters.test.tsx
- webapp/src/components/modals/channel_settings/channel_settings_filters.tsx
- webapp/src/components/react_select_setting.jsx
- webapp/src/testdata/jira-issue-metadata-helpers.ts
- webapp/src/types/model.ts
- webapp/src/utils/jira_issue_metadata.test.tsx
- webapp/src/utils/jira_issue_metadata.tsx
This PR adds tests for the `channel_settings_filter*` components.
https://mattermost.atlassian.net/browse/MM-19758
> [MM-19758] Write tests for filter components

- plugin.json
- server/manifest.go
- webapp/src/manifest.ts
> Bumped plugin version to v2.3.0

- webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap
- webapp/src/components/jira_epic_selector/jira_epic_selector.test.tsx
- webapp/src/components/modals/channel_settings/channel_settings.test.tsx
Tests will no longer have unhandled promises
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/427
> [MM-20142] Handle unhandledPromiseRejectWarning in test logs

- webapp/package.json
> Add jest watch command

- server/command_test.go
There was a mishap with a PR being merged without having latest master, causing a false positive in the tests. This is the second time this has happened in the recent past. Maybe we should always force an update with master before merging on plugin repos? @levb
> Fix help text test

- server/kv.go
- server/kv_mock_test.go
- server/stats.go
> Remove the ji arg of type Instance from UserStore interface method CountUsers

- webapp/src/components/modals/create_issue/create_issue.jsx
**Summary**
Observed: JavaScript error in the console after creating issue
Fixes #173
> When posting a response from the Jira plugin, we get React warnings in the console

- server/user_cloud.go
Add Site URL to third-party cookie error message.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/476
> Add Site URL to third-party cookie error message

- server/http.go
- server/issue.go
- server/issue_parser.go
- server/issue_test.go
**Summary**
[MM-17816] Add the ability to transition an issue after running `/jira view`
[https://mattermost.atlassian.net/browse/MM-17816](https://mattermost.atlassian.net/browse/MM-17816)
Fixes #422  
[MM-17816]: https://mattermost.atlassian.net/browse/MM-17816
> [MM-17816] Add the ability to transition an issue after running `/jira view`

- server/utils/utils_test.go
Fix failing build in go 1.14. See https://golang.org/doc/go1.14#net/url
> Fix test under go 1.14

- CODEOWNERS
- readme.md
PR for adding a CODEOWNERS file and mentioning the maintainers in README.md.
community-release.mattermost.com/core/pl/s59on6wz6tyufj8yy448yti3bo
> Add CODEOWNERS and maintainers

- docker-compose.yml
- readme.md
Some updates to the readme as well. Rendered [here](https://github.com/mattermost/mattermost-plugin-jira/blob/7dfe9fd76f1880e36fafabf91df08e0516b73924/readme.md).
@aaronrothschild We need to discuss the process how we want to propagate additional README changes to GitBooks. Should we create a new PR for every change to the README, or update in batches?
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/515
> Add docker-compose.yml to spin up Jira Server instance

- server/client.go
- server/issue.go
- server/utils.go
Recognize embeddable attachments and just link the rest of the attachments.
https://github.com/mattermost/mattermost-plugin-jira/issues/506
> [GH-506] Correctly link or embed attachments

- server/client.go
Fixes a nil pointer check
Fixes #537
> Fixed a nil pointer check

- webapp/src/components/form_button.jsx
The spinner was broken and showing a rotating square instead of the rotating dots. This adds the appropriate class name changes. 
https://mattermost.atlassian.net/browse/MM-24699
> [MM-24699] fix spinner

- server/command.go
- webapp/package-lock.json
Replace old doc link with link to gitbook documentation.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/545
> change link to documentation

- server/command.go
Cherrypick of https://github.com/mattermost/mattermost-plugin-ee-jira/pull/92 from enterprise repo
> Cherrypick "Make it so subscribe autocomplete shows for all users"

- plugin.json
- server/manifest.go
- webapp/src/manifest.ts
Bump version to prep for release
fixes: #628
> Bump version to v3.0.0-beta2

- docs/admininstrator-guide/notification-management.md
- docs/admininstrator-guide/permissions.md
- docs/admininstrator-guide/troubleshooting.md
- docs/administrator-guide/frequently-asked-questions-faq.md
- docs/end-user-guide/getting-started.md
- docs/end-user-guide/using-jira-commands.md
- docs/setup/configuration.md
- docs/setup/updating-the-plugin.md
Updated to align with 2.3 changes. Grammar, structure, trailing spaces.
> Jira 2.4 docs update

- server/command.go
> Fix typo in help command

- docs/README.md
- docs/SUMMARY.md
- docs/admininstrator-guide/administrator-slash-commands.md
- docs/end-user-guide/faq.md
- docs/end-user-guide/using-jira-commands.md
- docs/setup/configuration.md
- docs/setup/installation.md
Updates for https://github.com/mattermost/mattermost-plugin-jira/issues/579.
> Updates for Jira 3.0

- server/command.go
Same bug as for GH
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/683
> Post command response in RHS if triggered from there

- server/plugin.go
Check autolink status before using it.
Fixes #624
> [GB-624] Check autolink status before use

- server/command.go
- server/http.go
- server/issue.go
- server/issue_parser.go
- server/issue_test.go
Adds a "share" button to the ephemeral messages about jira issues (when viewed or created with slash commands) so that the user can press it and instantly share it with everyone on the channel.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/691
> Gh 691 share issue public

- docs/setup/configuration.md
Fix formatting issue in GitBook: https://mattermost.gitbook.io/plugin-jira/setup/configuration
> Fix formatting for GitBook

- server/command.go
- server/instances.go
- server/instances_test.go
This PR aims to solve #719 
#719
> [Fix: #719]: Correct error messages for multiple Jira instances

- docs/setup/configuration.md
> Clarify webhook source

- server/http.go
- server/issue_test.go
- server/user.go
- webapp/src/plugin.tsx
We were showing a connect success message when we update user defaults
> Only show connect ephemeral when user connects

- server/command.go
- server/instances.go
This PR aims to solve #722 
#722
> [Fix:#722] : Check errors for LoadInstances() call 

- plugin.json
- server/plugin.go
- server/subscribe.go
- server/subscribe_test.go
- server/webhook.go
- server/webhook_http.go
- server/webhook_http_test.go
- server/webhook_worker.go
- When a subscription posts to a channel, show the subscription name in the post
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/700
> Show subscription name in post when a subscription posts to a channel

- docs/setup/configuration.md
> Fix docs formatting

- readme.md
> Clarify Enterprise required for multiple instances

- CODEOWNERS
- readme.md
I spoke with @jfrerich and @levb about this online, and they have both given me the "ok" to make this change. I would like to be a reviewer of all PRs coming into this repo, and this is the most straightforward way to do this.
> Update code maintainers

- server/user_server.go
This PR fixes the HTML error page when `/jira connect` fails for a Jira Server instance. Right now there is a `not authorized` message above a bunch of raw HTML, rather than just rendering the HTML.
Fixes https://mattermost.atlassian.net/browse/MM-34683
> [MM-34683] Fix jira server html error page

- docs/administrator-guide/frequently-asked-questions-faq.md
- docs/administrator-guide/notification-management.md
Fixes https://github.com/mattermost/docs/issues/4754
> Update troubleshooting docs to clarify for legacy webhooks

- docs/SUMMARY.md
> Update SUMMARY.md (TOC file)

- server/plugin.go
> updated error message

- plugin.json
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/843
> Require Mattermost 6.5.0

- server/setup_flow.go
The first step on creating app link was a bit misleading for me, mostly due to JIRA's onboarding description of the checkboxes (attachments), so I think this small change could help someone.
> Updating info over first step on app link creation

- docs/setup/configuration.md
Documentation - Fix typos
Change _webhhok_ to _webhook_
Change duplicate _Step 3_ to _Step 4_
> Documentation - Fix typo in command

- assets/templates/command/install_server.md
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/907
> Update install instructions to include Jira 9 hint

- server/client.go
- server/client_cloud.go
- server/client_server.go
- server/issue.go
- server/plugin.go
Cherry-picked the merged commit from PR https://github.com/mattermost/mattermost-plugin-jira/pull/915 into branch release-3.2 due to the comment https://github.com/mattermost/mattermost-plugin-jira/pull/915#issuecomment-1453522988.
> [GH-912]:Cherry picked changes from #PR 915

- server/command.go
- server/plugin.go
- server/setup_flow.go
- server/telemetry.go
- server/user.go
Previously errors returned from the telemetry tracker didn't get logged. This PR adds proper log messages for all errors the telemetry tracker returns.
https://mattermost.atlassian.net/browse/MM-51269
> [MM-51269] Log errors from telemetry events

- readme.md
Final editorial pass of the repository's README content. Aligning updates across all GitBook migrations.
> README editorial pass

- readme.md
Fixes: https://github.com/mattermost/mattermost-plugin-jira/issues/920
> Removed unsupported webhook event types

- plugin.json
> Bump version to 4.0.1

- server/instance_cloud_oauth.go
Fixed the links for the Jira webhook page and Jira application links page.
Fixes #1012
> [MM-49] Fix invalid Jira links in posts

- webapp/package-lock.json
- webapp/package.json
Fixed security issue 
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/1
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/29
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/42
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/38
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/55
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/41
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/48
> Bump the versions of different packages to fix the security issues

- webapp/package-lock.json
- webapp/package.json
Removed the JS to TS Package as it was unused
> Removed the JS to TS Package as it was unused

- webapp/package-lock.json
- webapp/package.json
Removed react-js-to-ts package as it was unused.
> Removed react-js-to-ts package as it was unused

- readme.md
1) Updated the read me to clarify the /jira setup commands and other steps for setup  as well.
> Updated the readme to clarify the /jira setup commands and other steps for setup

- readme.md
Jason is no longer working on this project and so I've removed the reference to him in the README
> Remove co-maintainer from readme

- server/command_test.go
- server/instance_cloud_oauth_migration_test.go
- server/kv_migrate_test.go
- server/plugin_test.go
- webapp/junit.xml
- Replace AnythingOfTypeArgument with AnythingOfType
Fixes #1030
> [GH-1030] Replace AnythingOfTypeArgument with AnythingOfType

- plugin.json
- Update doc links in system console
Fixes #1029
> [GH-1029] Update doc links in system console

- webapp/src/types/model.ts
- webapp/src/utils/jira_issue_metadata.tsx
- webapp/src/utils/styles.ts
Fixed the Typescript errors in the web app's util files.
> [MM-669]: Fixed the TS errors in webapp's util files

- server/subscribe.go
- server/utils.go
- Added conditional to avoid posting multiple notifications in case of duplicate subscriptions
- Not getting multiple notifications in a channel in case of duplicate subscriptions.
1. Connect you Jira account.
2. Create multiple subscription fora same event.
3. Trigger the desired event from Jira.
Fixes  #1011
> [GH-1011] Added conditional to avoid posting multiple notifications in case of duplicate subscriptions

- plugin.json
- Updated doc links in system console settings
Fixes https://mattermost.atlassian.net/browse/MM-60323
> [MM-60323] Updated doc links in system console settings

- server/issue.go
- server/webhook_parser.go
- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
- Fixed the rendering of hyperlinks in the  tooltip
-  Fixed the rendering of hyperlink in issue events related to webhook notifications
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1081
- Connect your Jira to mattermost
- Subscribe to Jira project
- Create a Jira issue within the same project with a link in its description
- Check the subscription post in mattermost
> [MM-1081]: Fixed the rendering of hyperlink in tooltip

- webapp/src/actions/index.ts
- webapp/src/components/modals/attach_comment_modal/index.ts
- webapp/src/components/modals/channel_subscriptions/index.ts
- webapp/src/components/modals/connect_modal/index.ts
- webapp/src/components/modals/create_issue/index.ts
- webapp/src/components/modals/disconnect_modal/disconnect_modal_form.tsx
- webapp/src/components/modals/disconnect_modal/index.ts
- webapp/src/selectors/index.ts
- webapp/src/types/model.ts
- webapp/src/types/store.ts
Added type for redux store and resolved TS errors in a few files
- Attach comment modal
- Channel subscription
- Connect modal
- Create Issue modal
- Disconnect modal
> [MM-959]: Added type for redux store and resolved some TS errors

- .gitignore
Add Aider files to `.gitignore`
NONE
> Add aider files to gitignore

- server/webhook_parser.go
- server/webhook_parser_misc_test.go
Fix the issue of user mentions not rendering properly
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1189
> Fix issue of user mentions not rendering properly

- server/setup_flow.go
fixed plugin usage link in  setup flow
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1198
> fixed plugin usage link in  setup flow

- readme.md
Update readme.md to correct integrations link
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1211
> Update readme.md to correct integrations link

- server/webhook_jira.go
- webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.test.tsx
- webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx
- Add validation to subscription and Subscription Template creation
- Resolved jumbled file upload name issue
Partially Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1226
> Add validation to subscription creation and resolve jumbled file upload name issue
