glide.lock, plugin.go, plugin.yaml, plugin_test.go
This fixes the plugin to work with the most recent plugin API breakages in 5.2 by just using `GetChannelByNameForTeamName`.
=> Leverage GetChannelByNameForTeamName

server/configuration.go, server/plugin.go, server/plugin_test.go
See https://mattermost.atlassian.net/browse/MM-13581
=> Fix config auto unmarshalling

server/plugin.go
I missed an `return` in #16. Because of this `attachment` could be `nil` which caused `ParseSlackAttachment()` to panic and cause the problem reported in https://github.com/mattermost/mattermost-plugin-jira/issues/15#issuecomment-456833546.
I will submit a PR to `mattermost-server` to also fix this server-side.
=> Fix missing return

plugin.json, server/manifest.go
I want to release this to fix an NPE multiple user reported.
This NPE will also be fixed server side in v5.8, but since it's a annoying bug, releases a bugfix release is necessary IMO.
The only diff the previous version is https://github.com/mattermost/mattermost-plugin-jira/commit/5c62e8987f4df590d45ee84953f114f5bba322c4.
=> Bump version to 1.1.1

server/format-markdown.go, server/format-markdown_test.go, server/format-slack-attachment.go, server/format-slack-attachment_test.go
I am not sure why go vet decided to complain about this one, renamed `type parsed` to `type parsedWebhook` to eliminate the naming conflict. 2/5 it reads better now anyway.
=> Fixed go vet shadow variable

server/format-markdown.go
This was overlooked in https://github.com/mattermost/mattermost-plugin-jira/pull/22
I verified that all pointer fields of Webhook are nil-checked now.
This has been deployed to community-daily, and now new issues are displayed.
=> Fixed a nil pointer panic on empty Fields.Priority in new issues

server/command.go
Feedback welcome. Includes
- text updates for /jira help
- text updates for error responses
- JIRA > Jira
=> Proposed text updates for /jira slash commands

plugin.json, server/http.go, server/instance_cloud.go, server/instance_server.go, server/kv.go, server/message_posted.go, server/templates/atlassian-connect.json, server/user.go, server/user_atlassian_connect.go, server/user_oauth1.go, server/utils.go, server/webhook.go, webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
1. JIRA > Jira throughout error texts and user-visible strings
2. Help text update for Jira Server URL config setting
=> Some cleanup for Jira plugin

README.md
The Jira Server install docs is how this is currently implemented, but we'll likely update this prior to the release.
=> Doc updates for roadmap and Jira Server install docs

server/command.go
When running `/jira instance delete 1` with only one instance, it would respond with: `Wrong instance number 1 must be 1-1`. 
Also, calling `delete` with no instances would give a similar response.
=> small fixes to /jira instance delete

server/command.go, server/instance_server.go, server/webhook.go
This PR fixes the issue that we'd receive the secret double-%-escaped. This is to unescape the secret repeatedly until there are no more valid %hh sequences left, comparing each version.
@jasonblais I am not sure there was a prior (1.0) ticket on this, couldn't find it. This may or may not be the same issue, but should be a general improvement anyway. I'd prefer that the secret was base64-encoded but I don't think it's better to stick with a backwards-compatible approach.
Also added `/jira webhook` command to see a URL custom-fit to the current channel.
=> Fixed a bug in unescaping webhook secret

webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/modals/create_issue/create_issue.jsx, webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
1. Update post menu text from "Attach Jira Issue" to "Attach to Jira Issue" to clarify the message would be attached TO a Jira issue.
2. Update "Create Jira Ticket" title in issue creation screen to "Create Jira Issue"
3. Update texts in "Attach Message to Jira Issue" screen
- `Attach Message To ...` in title to `Attach Message to...`
- Update input text for "Project" field to `Select...`. This is for consistency with the new Jira issue creation screen.
- Update input text for "Issue Key" field to `Enter issue key to attach message to, e.g. EXT-20`.
=> Update few texts in post menu and Attach/Create Jira issue screens

server/command.go, server/issue.go
**Summary**
This PR changes the ephemeral message from a generic message to a message that verifies to the user that the state was changed for a specified issue.
Example of new messages:
Please view the following ticket for a description
https://mattermost.atlassian.net/browse/MM-15533
=> [MM-15533] Change ephemeral message to <issue-key> transitioned to <state>

webapp/src/components/input.jsx, webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/modals/create_issue/create_issue.jsx, webapp/src/components/setting.jsx
=> MM-15535 - UI updates for Jira 2

server/command.go
1. Fix typo (Disonnect > Disconnect)
2. Consistency in terms of first-person vs third-person terms, e.g. `Change` , `Changes`
3. Consistency with capitalization
4. Update "server Jira instance" to "Jira Server or Data Center instance"
5. Update "cloud Jira instance" to "Jira Cloud instance"
6. Capitalize "System Administrators"
7. Remove an ending period
=> Minor modifications to "/jira help" text

server/webhook.go, server/webhook_markdown_test.go, server/webhook_slack_attachment.go, server/webhook_slack_attachment_test.go
Discussed with @jasonblais offline - some small improvements:
- Added the issue description to the headline of the posts
- Remove the (now redundant) headline from the Slack attachment
- Do not use Slack attachments for 1-liners
https://mattermost.atlassian.net/browse/MM-15866
=> MM-15866: Webhook presentation tweaks in jira2

webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js, webapp/src/components/post_menu_actions/create_issue/create_issue.jsx, webapp/src/components/post_menu_actions/create_issue/index.js, webapp/src/selectors/index.js
@jfrerich there was just one minor conflict when merging, please check
* When Jira instance exists, but user is not connected, only show one
"connected to jira" post menu item.  This checkin is the cheapest
solution which basically uses create issue as the master for dispaying
the "connect to jira" menu option.
* Consolidate lines and remove extra if statement.
* Add isConnected selector and return as bool from mapStateToProps in
post_menu_actions/attach_comment_to_issue/index.js and
post_menu_actions/create_issue/index.js
Add Jira icon to "Connect to Jira" post menu item
=> [MM-15536/MM-15832] Only show one "Connect to Jira" menu option. (#66)

server/issue.go
Fixes: When creating a Jira issue from a post that is a reply post issue creations appears to fail
[MM-15762](https://mattermost.atlassian.net/browse/MM-15762)
=> [MM-15762] detect if the post is a reply and send the correct fields

server/atlassian_connect.go, server/command.go, server/http.go, server/instance.go, server/instance_cloud.go, server/kv.go, server/user.go, webapp/src/action_types/index.js, webapp/src/actions/index.js, webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js, webapp/src/components/post_menu_actions/create_issue/create_issue.jsx, webapp/src/components/post_menu_actions/create_issue/index.js, webapp/src/plugin.jsx, webapp/src/reducers/index.js, webapp/src/selectors/index.js
The 'Connect to Jira' menu item will not appear if there is no installed Jira instance.
Notes:
- One edge case: When connecting server, if a user was already connected to that server, their client won't be updated until they reload. Possible second ticket @jasonblais ?
- Some refactoring  (eg. state variables to make it more clear, connected -> userConnected)
- now using `/jira uninstall cloud/server <URL>`, and the cloud server's callback to ACUnistalled does nothing because we can't authenticate it with the JWT. 
[MM-15537](https://mattermost.atlassian.net/browse/MM-15537)
[MM-15828](https://mattermost.atlassian.net/browse/MM-15828)
=> [MM-15537] Fix 'connect to jira' menu item when not connected

server/webhook.go
This PR addresses issue (B) that was found in https://mattermost.atlassian.net/browse/MM-15439
The "old view" in Jira cloud was sending an issue_updated, rather than an issue_assigned webhook.
=> Webhooks - Jira cloud old view assignee

server/atlassian_connect.go, server/command.go, server/http.go, server/instance.go, server/instance_cloud.go, server/kv.go, server/user.go, webapp/src/action_types/index.js, webapp/src/actions/index.js, webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js, webapp/src/components/post_menu_actions/create_issue/create_issue.jsx, webapp/src/components/post_menu_actions/create_issue/index.js, webapp/src/plugin.jsx, webapp/src/reducers/index.js, webapp/src/selectors/index.js
@cpoile - again, a slightly non-trivial merge, please verify
[MM-15537] Fix 'Connect to Jira' menu item when not connected
* * keep one API endpoint: userinfo can give both isntance and connected
* * remove httpAPIGetInstanceStatus
* PR comments, and implemented MM-15828
* finishing up MM-15828
* minor cleanup
* Update server/command.go
Co-Authored-By: Jason Blais <13119842+jasonblais@users.noreply.github.com>
* Update server/command.go
Co-Authored-By: Jason Blais <13119842+jasonblais@users.noreply.github.com>
* Update server/command.go
Co-Authored-By: Jason Blais <13119842+jasonblais@users.noreply.github.com>
* Update server/command.go
Co-Authored-By: Jason Blais <13119842+jasonblais@users.noreply.github.com>
* Update server/command.go
Co-Authored-By: Jason Blais …
=> [MM-15537] Fix 'connect to jira' menu item when not connected (#75)

webapp/src/components/jira_field.jsx, webapp/src/components/jira_fields.jsx, webapp/src/components/modals/create_issue/create_issue.jsx
… (#81)
The priority field type, inside the fields object, is an object, not a string value.
For the priority ReactSelectSetting component, filter against
this.props.value.id to get the value, not this.props.value which is an
object
Remove default values in initialState object.
Remove special casing for priority field in JiraField component. Note
that fields that have field.allowedValues will return an object.
Otherwise returns a string with is handled when field.schema.type ===
'string'
minor changes
fixup
=> [MM-15589] Create Issue: (Jira server) Priority field fails to select… #102

webapp/src/components/jira_field.jsx
Summary
This PR handles two issues, both for custom Jira fields
1) if the custom field is a textarea, mimic that in the create-issue dialog window.
2) Select List (single choice) field.  Values were not showing up in the dropdown.
Ticket Link
Please view the following ticket for a description
https://mattermost.atlassian.net/browse/MM-15838
=> [MM- 15838] Handle selected elements in Jira issue creation screen

webapp/src/components/jira_field.jsx, webapp/src/components/jira_fields.jsx
**Summary** 
This ticket is to reduce the fields that show up in the create issue dialog window to only those currently supported.
- Allow fields that are not required to show up in create issue dialog
- restrict custom field types to textarea, textfield, select (single-select), epic-label (for epic issue types), and project picker
- for non-custom types, with allowedValues, don't show fields with field.schema.type == array.  Fix at later date
https://mattermost.atlassian.net/browse/MM-15962
=> [MM-15962] Allow only handled fields to show in Create Issue Dialog

webapp/src/components/jira_issue_selector/jira_issue_selector.jsx, webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/react_select_setting.jsx, webapp/src/components/utils.jsx
**Ticket:**
https://mattermost.atlassian.net/browse/MM-15922
I've also styled the Jira issue selector but I'm basically using the same style function as in the `react_select_setting.jsx` file. Would be ideal if we can just have a separate utils.jsx file from where we can import the function in different places.
=> MM-15922 - Fixing theme and dropdown issue

webapp/src/components/jira_field.jsx, webapp/src/components/jira_fields.jsx
cc @jfrerich 
- restrict custom field types to textarea, textfield, select
(single-select), epic-label (for epic issue types), and project picker
- for non-custom types, with allowedValues, don't show fields with
field.schema.type == array.  Fix at later date
=> - Allow fields that are not required to show up …(#112)

server/user_cloud.go
- Instead of displaying nickname, display "fullname (@username)" or "@username" if user has no fullname set.
- This makes it easier for the user to understand what is being connected.
[MM-15932](https://mattermost.atlassian.net/browse/MM-15932)
=> [MM-15932] In Jira Connect approval page, display a better name

server/issue.go, webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/modals/attach_comment_to_issue/index.js, webapp/src/components/modals/create_issue/create_issue.jsx, webapp/src/components/modals/create_issue/index.js
Can now create issues from DM posts, and attach to Jira issues from DM posts. Works by sending in the team name from the webapp component. As a bonus: making a permalink is less code now.
Fixes: [MM-15948](https://mattermost.atlassian.net/browse/MM-15948)
=> [MM-15948] Create and attach issues to DM posts by sending in teamname

webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/modals/create_issue/create_issue.jsx
- Setting a couple attributes on the bootstrap modals fixes the problem.
Fixes: [MM-15938](https://mattermost.atlassian.net/browse/MM-15938)
=> [MM-15938] Prevent modal closing on clicking or keyboard escape

.gitignore, server/testdata/webhook-server-comment-created.json, server/testdata/webhook-server-issue-updated-comment-deleted.json, server/testdata/webhook-server-issue-updated-comment-edited.json, server/testdata/webhook-server-issue-updated-commented.json, server/webhook.go, server/webhook_markdown_test.go, server/webhook_slack_attachment.go
Ticket: https://mattermost.atlassian.net/browse/MM-15893. I did not observe failures with anything other than comments, which I fixed.
Jira Server and Jira Cloud send different webhooks for comments. 
- Jira Cloud sends 1 webhook (A) for each comment event, with `WebhookEvent == "comment_xxx"`. The event contains all necessary issue data for us to post to Mattermost. 
- Jira Server sends 2 webhooks for each comment change. Like Jira Cloud, it sends a (B) `WebhookEvent == "comment_xxx"` event, but it is stripped of all issue data. It also sends a (C) `WebhookEvent == "jira:issue_updated" && IssueEventTypeName == "comment_xxx"` which are complete, like (A).
For our context, (B) is insufficient, so it now returns `ErrWebhookIgnored` and results in a no-op. (C) is now supported, but it lacks …
=> MM-15893: Fixed Jira Server webhooks

server/issue.go, webapp/src/components/modals/create_issue/create_issue.jsx
**Summary**
If a user does not have permissions to create issues, alert them in the create issue dialog window.  Previously, the dialog window hung in the "loading" state.
*New Dialog Window*
- Message added
- Cancel and Create buttons changed to singe Close button.
**Testing** 
Tested on sales-jira instance
**Repro**
*disable create issue permissions*
- Jira Administration > Issues > Permission schemes > Default software scheme > Permissions
- Create Issues > Edit > Remove 
- Removes Application access for Any logged in user
*reenable access*
- Permission > Add `Create Issues` label
- Granted to > Application access > Any logged in user
**Ticket**
Please view the following ticket for additional description
https://mattermost.atlassian.net/browse/MM-15986
=> [MM-15986] Check if user does not have permissions to create issues

server/issue.go, webapp/src/components/jira_field.jsx, webapp/src/components/jira_fields.jsx, webapp/src/components/modals/create_issue/create_issue.jsx
**Summary** 
This ticket addresses the issue when a user tries to create a ticket and the connected Jira instance requires fields we currently don't support.
I'm using the Draft Pull Request feature because there are some steps still remaining, but I would like to receive early feedback due to the time crunch for Jira2.0 
**Description of enhancements made for UX (from Ticket)**
Update UX when creating issues for projects that require additional fields
step 1: allow the user to fill in the parameters we support in the Create Jira Issue dialog
step 2: allow user to hit "Create"
step 3: respond back with an ephemeral message saying
>The project you tried to create an issue for has **required fields** this plugin does not yet support. Please [create your Jira issue manually](...link to …
=> [MM-15913] Update UX when creating issues for projects that require additional fields

server/issue.go, webapp/src/client/index.js, webapp/src/components/form_button.jsx, webapp/src/components/input.jsx, webapp/src/components/jira_issue_selector/jira_issue_selector.jsx, webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
- When a user has access to browse a project but does not have access to add comments to the issue, Attach to Jira Issue fails silently
- Also some clean-up:
- some proptypes were marked as required but weren't actually required causing red in the console
- forgot to remove the project props in the attach-to-issue search (we're not filtering by project anymore)
UX:
[MM-16097](https://mattermost.atlassian.net/browse/MM-16097)
=> [MM-16097] Fixing: Attach to Jira Issue fails silently when user lacks permissions

plugin.json, server/http.go, server/plugin.go, server/user.go, webapp/src/actions/index.js, webapp/src/plugin.jsx
- added a system console setting
- opened up a new API endpoint (didn't think it belonged in the user info, and needed this settings info before the userInfo)
- it's quick and dirty -- the system console settings changes are not pushed to the clients, so if they had the ability to use the UI, they will still have it until they refresh. Open to any suggestions if you think it's too simplistic.
UX:
[MM-16098](https://mattermost.atlassian.net/browse/MM-16098)
=> [MM-16098] Add a plugin.json setting to allow disabling of all Jirav2 UI features

server/issue.go, webapp/src/components/modals/create_issue/create_issue.jsx
**Summary**
This ticket solves two problems. 
1. When a user tries to create a Jira issue and Jira is in a state that requires fields that do not show up in the creation window, Jira will fail.  This actually happens in the Jira instance create issue window.   When this case occurred, the create issue dialog window would allow the user to hit create and provide no feedback.  Now, a link is provided in an ephemeral MM post that takes the user to Jira with the handled fields pre-populated.  From here, the user will see the fields that are failing and can resolve by working with their Jira Admin.
Here is a sample of the response:
2. When the user clicks the create button and Jira responds with an error, post the error in the create issue dialog window.
Here is a sample of this response type: …
=> [MM-15924] Server-side error handling for create/attach Jira issue dialogs

webapp/src/components/input.jsx, webapp/src/components/jira_field.jsx, webapp/src/components/jira_fields.jsx, webapp/src/components/jira_issue_selector/index.js, webapp/src/components/jira_issue_selector/jira_issue_selector.jsx, webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/modals/create_issue/create_issue.jsx, webapp/src/components/react_select_setting.jsx, webapp/src/components/validator.js
- Display a client-side error when the user clicks submit and there are empty fields marked `required`.
- Removed the built in validation for input fields (bootstrap?) because @jasonblais found that these errors did not display in the desktop app. Replaced with this method. 
- For now, the validation is simply whether or not it is required, and if so make sure it's not empty. Can be improved as needed.
Unrelated fixes:
- Found a few problems with required props, fixed those.
- Should be using find instead of filter in react-select value fields.
Looks like:
[MM-16229](https://mattermost.atlassian.net/browse/MM-16229)
=>  [MM-16229] Implement proper client-side error handling for create/attach Jira issue dialogs

webapp/src/components/jira_field.jsx
Uses a custom component to render options that has icon if available. Avoids the issue of component labels not being searchable without special casing priority.
Replaces: https://github.com/mattermost/mattermost-plugin-jira/pull/156
=> MM-16116 Fix serching in single select dropdowns.

webapp/src/components/setup_ui.js, webapp/src/plugin.jsx
- use a dummy root component that will set up the UI once the user is logged in
- Fixes [MM-16309](https://mattermost.atlassian.net/browse/MM-16309)
- Requires https://github.com/mattermost/mattermost-webapp/pull/2966
=> [MM-16309] use a dummy root component to detect when user is logged in

plugin.json
State that EnableJiraUI allows users to attach and create Jira issues in Mattermost. When disabled, users aren't able to take these actions.
Fixes https://mattermost.atlassian.net/browse/MM-16098
=> MM-16098 Clarify what exactly EnableJiraUI enables

Makefile, server/command.go, server/instance_cloud.go, server/instance_server.go, server/issue.go, server/kv.go, server/user.go, server/user_cloud.go, server/user_server.go
- Tried to reduce the use of `.Name` to the minimum outside of Jira
Server-specific code.
- removed rather than change `LoadMattermostUserId()` since it is not used
in this version
- Also patched `make deploy` to the current Token header format
Ticket: https://mattermost.atlassian.net/browse/MM-16364
=> MM-16364 Use AccountID as applicable rather than Name

webapp/src/plugin.jsx
Multiple dropdown items were being registered. This prevents that. 
If you can think of a better way, would be nice.
=> Don't setupUI more than once

server/command.go, server/issue.go, server/issue_parser.go, server/webhook_parser.go
- Adds a `/jira view` command
- As described in the ticket: Makes the default command point to view, e.g. `/jira issue`.
- Not reusing the webhook parser; wrote a new one. Correctly handles jira messages now.
UX looks like:
[MM-15229](https://mattermost.atlassian.net/browse/MM-15229)
=> [MM-15229] Add "/jira view <issuekey>" command

webapp/src/actions/index.js, webapp/src/hooks/hooks.js
- Check on the client-side whether the user is connected. If they aren't, send an ephemeral message.
- Also checks if the instance is connected (because if the instance is deleted while a user is connected, then the user tries to create, it would just hang).
PM review: 
The messages are: 
- `There is no Jira instance installed. Please contact your system administrator.`
- `Your username is not connected to Jira. Please type '/jira connect'.`
Links:
- Fixes: [MM-15786](https://mattermost.atlassian.net/browse/MM-15786)
=> [MM-15786] /jira create without an installed Jira instance throws a 500 and hangs the create modal

webapp/src/utils/styles.js
- Tracked the problem down to CSS. 
- One word change fixes it.
Asaad: 
- Would this break how you expect the UX to work? We're not highlighting the item that's already selected (the one already in the text area of the select box) we're highlighting the item that they are hovering over or currently cursoring through.
- Fixes [MM-16528](https://mattermost.atlassian.net/browse/MM-16528)
=> [MM-16528] Currently selected options in single select list are not highlighted

server/kv.go, server/user_cloud.go, server/utils.go, server/webhook.go, server/webhook_http.go, server/webhook_parser.go
- Jira Cloud will only send accountID soon, so start mapping that to MattermostID in the store
- send notifications based on either username (Server) or accountId (Cloud)
- fix notifications on master
- Requires users to disconnect and connect for us to map the accountId -> MattermostID
- Fixes [MM-16508](https://mattermost.atlassian.net/browse/MM-16508)
=> [MM-16508] Fixes notifications on master; and for Jira Cloud's recent changes

webapp/src/components/jira_issue_selector/jira_issue_selector.jsx, webapp/src/components/modals/create_issue/create_issue.jsx
This PR address error handling for create and attach issue modals
In the event the `/api/v2/get-create-issue-metadata` endpoint returns an error, the create issue modal will only show the error and a close button.
In the event createIssue API call to Atlassian fails, show the error, but keep the modal open and allow user to resolve the issue.
Server-side errors are now shown above the `Jira Issue` drop down.  These are errors which would return from the '/api/v2/get-search-issues` endpoint.
Testing a an error from create issue API call is easy to test.  Using the summary field, add text >255 characters.
For the failed endpoints below, I am not sure how to test these or force these errors.  I manually added a return statement with a failure message for each.
'/api/v2/get-search-issues` …
=> [MM-16404] Fix Error Handling for Attach and Create issue Modals

webapp/src/client/index.js, webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
- Small merge error: should return promises
- Also, should have a default options object for requests (or else we get a `TypeError: Cannot read property 'method' of undefined` error).
- Fixes [MM-16641](https://mattermost.atlassian.net/browse/MM-16641)
=> [MM-16641] Attach message to issue search is broken on master

webapp/src/actions/index.js
- Problem: Using "/Jira install" to replace the current Jira instance causes incorrect post menu options in Mattermost client
- Solution: send a getConnected request when the instance state changes
- Fixes [MM-15902](https://mattermost.atlassian.net/browse/MM-15902)
=> [MM-15902] When `/jira install` changes the instance, the UI is stuck in the previous state

server/command.go, server/instance_cloud.go, server/kv.go
There was a typo before `json:"none"` rather than `json:"-"`, leading to
the context getting (re-)stored in the DB unintentionally.
The intention was to store the original JSON regardless of what fields
we extract from it in run-time, now properly implemented.
Also updated the commented debug code in command.go so it compiles + formatting VSCode flavor.
=> Properly load Atlassian security context in LoadInstance

server/http.go, server/issue.go, webapp/src/action_types/index.js, webapp/src/actions/index.js, webapp/src/components/modals/channel_settings/channel_settings.jsx, webapp/src/components/modals/channel_settings/channel_settings_internal.jsx, webapp/src/components/modals/channel_settings/index.js, webapp/src/components/modals/create_issue/create_issue.jsx, webapp/src/components/modals/create_issue/index.js, webapp/src/reducers/index.js, webapp/src/selectors/index.js, webapp/src/utils/jira_issue_metadata.jsx
- From Jira we're requesting the minimum from the create-issue-metadata rest endpoint. Even that's pretty big, but we have to request it per user to see what projects the user can create issues in. On the server we're reducing that to pre-formatted value-label arrays for the projects and issues react-select dialog boxes. 
- Together, that reduces what's sent to client (from 113Mb to 885kb)
- When a user selects a project, that's when we request the full details of its fields. But that's pretty quick and there's a loading component for that brief wait.
- eg: Switching to a new project will erase the old jiraIssueMetadata object in the store (which replaces the fields components with the loading component), request the selected project's metadata, and display the new fields when …
=> [MM-16108] streamlined createIssueMetadata to support 5000+ projects

server/webhook_http.go, server/webhook_http_test.go, server/webhook_parser.go
- An update to #216 after @jasonblais pointed out another way multiple events can be sent (press edit on an issue).
- Added "reporter" changelog event
- Changed how description is formatted so it makes more sense (and a strikethrough won't work if there's markdown formatting in the description)
UX, looks like:
- [MM-15927](https://mattermost.atlassian.net/browse/MM-15927)
- updates: #216
=> MM-15927 ChangeLog parsing should scan and post all supported events (pt 2)

webapp/src/action_types/index.js, webapp/src/actions/index.js, webapp/src/components/modals/channel_settings/channel_settings_internal.jsx, webapp/src/reducers/index.js
This PR adds functionality to delete a channel subscription from the edit subscription modal.
https://mattermost.atlassian.net/browse/MM-16763
Opening modal again after subscription has been deleted:
=> [MM-16763] Delete subscription button added to channel subscription modal

plugin.json, server/http_test.go, server/plugin.go, server/subscribe.go, webapp/src/actions/index.js, webapp/src/client/index.js, webapp/src/components/modals/channel_settings/channel_settings.jsx
Implements these settings in the system console for JIRA:
Shows this when you don't have permissions to manage:
It's not ideal. When we implement the proper UI for this, we should show existing subscriptions, but restrict editing instead of just showing an error.
Hiding the button would be more work and may be a performance problem, so I avoided that.
@aaronrothschild Looking for PM review of the in the screenshots above.
=> MM-16881 Add ability to restrict permissions of subscribe.

server/webhook_parser.go
- refactor comment_created notifications and reuse for edited comments
- fixed an issue where we weren't adding the commentAuthor to the notification. A notification looked like:
Now looks like:
[MM-16933](https://mattermost.atlassian.net/browse/MM-16933)
=> MM-16933 Attach comment notifications for edited comments

server/http_test.go, server/kv_mock_test.go, server/subscribe.go, server/subscribe_test.go
This PR changes how the channel subscriptions are stored in the KV Store.
Instead of being stored at the key `JIRA_SUBSCRIPTIONS_KEY`, each instance's subscriptions will now be stored with their own key in the KV store. So when we access an instance's subscriptions we will use `store.keyWithInstance(ji, JIRA_SUBSCRIPTIONS_KEY)` for the key.
https://mattermost.atlassian.net/browse/MM-16940
=> Make channel subscriptions instance-specific

webapp/src/plugin_id.js
This PR makes the webapp read from config instead of hardcoding the plugin id.
The reason for this PR is so we can run different versions of a plugin on the same server by toggling them enabled/disabled.
=> Webapp should read plugin id from manifest

server/http.go, server/http_test.go, server/issue.go, server/subscribe_test.go, webapp/src/actions/index.js, webapp/src/components/modals/channel_settings/channel_settings_internal.jsx, webapp/src/components/modals/channel_settings/index.js, webapp/src/components/modals/create_issue/create_issue.jsx, webapp/src/components/modals/create_issue/index.js, webapp/src/utils/jira_issue_metadata.jsx
This PR allows the user to choose multiple projects for a channel subscription.
https://mattermost.atlassian.net/browse/MM-17061
https://mattermost-plugin-jira-test.test.spinmint.com/test/channels/town-square
=> [MM-17061] Support multiple projects for a channel subscription

plugin.json
It's not clear that `channel_admin` actually applies to team and system admins. Same for `team_admin`
=> Clarify options for RolesAllowedToEditJiraSubscriptions

server/webhook_worker.go
- Bug fix for async workers. Need to continue on an error so that we don't try to dereference or cast a nil pointer later on in the function.
- This was causing the plugin to crash when the comment edited webhook returned an `ErrWebhookIgnored`, causing the linked ticket.
- Good catch by @DHaussermann 
- Fixes [MM-17234](https://mattermost.atlassian.net/browse/MM-17234)
=> [MM-17234]  Users are not receiving DMs for jira @mentions

webapp/src/components/modals/create_issue/create_issue.jsx
- Fixed a merge mistake/regression
- We shouldn't require a post object to stop the `loading` component --- the `/jira create` slash command opens the model without a post object.
- Fixes [MM-17131](https://mattermost.atlassian.net/browse/MM-17131)
=> [MM-17131] Create slash command does not work to open the modal

webapp/src/components/modals/channel_settings/channel_settings.jsx
When the `Channel Jira Settings` modal is open, disable it from closing when clicking outside of it.
https://mattermost.atlassian.net/browse/MM-17105
=> [MM-17105] Prevent channel settings modal from closing when click outside of it

server/issue.go
When assigning a user to a ticket, the API returns an error if both `user.AccountId` and `user.Name` is defined on the single user. 
To fix this, I nulled the `user.Name` field of the user struct before calling `jiraClient.Issue.UpdateAssignee()`
Note other error handling functions of the `/jira assign` slash commands worked as expected.  This is because the errors are handled inside the server code, before calling the Jira API function.
https://mattermost.atlassian.net/browse/MM-17250
=> [MM-17250] reset user.Name to nil value before passing to UpdateAssignee method.

webapp/src/components/modals/channel_settings/channel_settings_internal.jsx, webapp/src/components/setup_ui/setup_ui.jsx, webapp/src/utils/jira_issue_metadata.jsx
- We were using `Array.flat()` which isn't polyfilled by Babel until core-js 3, which we won't have until 5.16. So, this PR manually polyfills the function.
- Unrelated cleanup: some props were marked as `required` but were being fetched async (so were often nil when the component was loaded) causing red in the console. I want to clean that up.
- Fixes [MM-17285](https://mattermost.atlassian.net/browse/MM-17285)
=> [MM-17285] Subscribe modal causes blank screen on desktop

plugin.json, server/subscribe.go, server/utils.go
- Working as intended. The permission that “Channel, …. Admin” means is can the user “manage channel settings”. (See the screencap)
- Protective change: trimmed the space around the allowed groups in case admins put a space after a comma.
Needs PM review:
- Added some info in the System Console to let admins know this is happening (line 38).
- [MM-17268](https://mattermost.atlassian.net/browse/MM-17268)
=> [MM-17268] Subscribe permission for "Channel, Team and System Admins" treats all users as Channel Admins

server/issue.go, server/utils.go
- We are now uploading file attachments when attaching a post to an issue.
- It's a little awkward to do it with Jira, you have to upload the attachment to the original issue, then add a reference to the attachment as text in the comment. 
- Looks like:
PM review:
- We're sending back notifications when the file attachments fail or when the comment fails to be updated. Line 534, and 580
- Fixes: [MM-17295](https://mattermost.atlassian.net/browse/MM-17295)
=> [MM-17295] Attach as comment should also append file attachments

webapp/src/components/setup_ui/setup_ui.jsx, webapp/src/plugin.jsx
- `componentDidMount` was being called many more times than expected. But the `setupUI` function was failing at the `registry.registerReducer`. This meant we were not showing multiple icons by accident. 
- Now we're explicitly flagging when we've set up the UI.
- tested: disconnecting/reconnecting, installing, uninstalling -- these all make the icons appear/disappear as expected because those are handled through websockets events
- Fixes [MM-17318](https://mattermost.atlassian.net/browse/MM-17318)
=> [MM-17318] Fix for multiple icons is working, but not sure why

server/command.go
We are normalizing the url used for the `/install` command but not the `/uninstall` command. This fixes the case where the user has a trailing slash in their url, and the uninstall fails.
=> Normalize url on uninstall

plugin.json, server/http.go, server/instance_cloud.go, server/instance_server.go, server/issue.go, server/plugin.go, server/utils.go, server/utils_test.go
- Adds a **hidden** config `MaxAttachmentSize`, defaults to 10Mb
- Limits upload-able attachment size
- Limits Jira HTTP response size
- Added a convenience `type ByteSize` to work with size values in config
- Includes, and effectively refactors https://github.com/mattermost/mattermost-plugin-jira/pull/248
https://mattermost.atlassian.net/browse/MM-17129
https://mattermost.atlassian.net/browse/MM-17133
=> MM-17129: HTTP and attachment size limits

plugin.json
Notes:
- Follow-up to concerns raised at https://mattermost.atlassian.net/browse/MM-17268 about what exactly the options for the RolesAllowedToEditJiraSubscriptions settings do.
- Proposal was posted here https://community-release.mattermost.com/core/pl/wb7ymm7jztfc7y6q9895ocpyse
- Partially reverts https://github.com/mattermost/mattermost-plugin-jira/pull/251
If other functional changes should be done, let me know.
=> MM-17268: Update display names for RolesAllowedToEditJiraSubscriptions

server/command.go
- Require user to post `/jira view <issue-key>` to preview a Jira issue, instead of posting `/jira <issue-key>`
- This was a tough one.
- [MM-17267](https://mattermost.atlassian.net/browse/MM-17267)
=> [MM-17267] Require user to post "/jira view <issue-key>" to preview a Jira issue

server/utils.go, server/webhook.go, server/webhook_parser.go
- Comment updates from Cloud include user names, so when we were looking up MM UserIds we were trying to look up by user name. But... we store cloud users by accountId. So prefer accountId.
- Fixes a bug found by Dylan: [MM-17312](https://mattermost.atlassian.net/browse/MM-17312)
=> MM-17312 Mentions in comments only work sometimes

webapp/src/components/modals/channel_settings/channel_settings_internal.jsx
Having multiple projects selected in the channel subscriptions modal makes many of the options confusing, as the choices are project-specific and they often don't overlap. We have chosen to scale back the feature for this release to include choosing only one project, and focus on providing multiple subscriptions per channel next release.
https://mattermost.atlassian.net/browse/MM-17467
=> [MM-17467] Use only one project in the channel subscriptions modal

webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
Fixes not being able to connect to JIRA using the buttons on the desktop app. 
Follow up issue fond in 2.1 where /jira connect opens in browser: https://mattermost.atlassian.net/browse/MM-17510
=> MM-17389 Fixing connect on desktop app.

server/command.go, server/user.go
This PR fixes the case where the plugin redirects the user to Jira when the user's Mattermost account is already connected.
https://mattermost.atlassian.net/browse/MM-17134
=> [MM-17134] Jira connect does not tell you if user has already been mapped

server/command.go
Made a change as we don't support `/jira <issue-key>` anymore
`/jira view <issue-key>` ~~or `/jira <issue-key>`~~ - View a Jira issue
=> Edit `/jira view` help text

server/command.go, webapp/src/components/setup_ui/setup_ui.jsx, webapp/src/hooks/hooks.js
Since the channel subscriptions modal does not feature everything we think it needs to for all end-users of an organization, we have decided to remove the channel subscriptions button from the channel header for now, and instead have a `/jira subscribe` command to open the modal. This is also an attempt to make it less intrusive for users that have only one plugin button in the channel header.
See the conversation about this decision here: https://community-release.mattermost.com/core/pl/agm7ar97opnf9g83h97pfwhkke
https://mattermost.atlassian.net/browse/MM-17583
I've removed some code that sets up the channel header button, but left the code that the parent component has to hook it up. The former was to make the linter happy, the latter was to make it easier to set up whatever component …
=> Introduce `/jira subscribe` command to open channel subscriptions modal

server/testdata/webhook-issue-updated-multiple-values.json, server/webhook_http_test.go, server/webhook_parser.go
This PR fixes the issue where the multiple changelog view applies a strikethrough to a blank value, resulting in "~~~~" being shown in the post. Instead, now we show a strikethrough "None", consistent with the single changelog view.
https://mattermost.atlassian.net/browse/MM-17507
=> [MM-17507] Fix issue where empty changelog value shows up as ~~~~

server/command.go, webapp/src/hooks/hooks.js
This PR makes it so when the `/jira connect` command is run in the desktop app, the redirect opens in a popup, rather than the browser.
This makes the server-side `connect` command useless, as it is now handled client-side. Should the command be outright removed from the server? 
https://mattermost.atlassian.net/browse/MM-17510
=> [MM-17510] Make `/jira connect` open in a popup for desktop app

server/issue.go
This PR fixes the issue where we assume an issue is being created through a post rather than `/jira create`. This has come up a few times now, so we may want to restructure the function so it is not as easy to make this error.
https://mattermost.atlassian.net/browse/MM-17662
=> [MM-17662] Check for nil post before uploading attachments

webapp/src/components/modals/channel_settings/channel_settings_internal.jsx, webapp/src/utils/jira_issue_metadata.jsx
This PR lets the webapp gracefully handle when a project is missing from an existing channel subscription. The modal would normally crash in this case. This PR also keeps into account deleted custom fields and issue types.
https://mattermost.atlassian.net/browse/MM-17614
=> [MM-17614] Handle error fetching project e.g. a project was deleted

Makefile
With the changes from #267 the new server-debug (sd) make command was failing. Now it doesn't.
#267 #255
=> Remove templates related command from Makefile

server/testdata/webhook-server-issue-updated-closed.json, server/testdata/webhook-server-issue-updated-in-progress.json, server/testdata/webhook-server-issue-updated-reopened.json, server/testdata/webhook-server-issue-updated-resolved.json, server/webhook_http_test.go, server/webhook_parser.go
This PR adds in the functionality to support the `issue_resolved` sub-event type when parsing the Jira Server webhook.
Edit: `issue_closed`, `issue_reopened`, and `issue_work_started` are also now supported.
https://mattermost.atlassian.net/browse/MM-17750
[https://github.com/mattermost/mattermost-plugin-jira/issues/272 ](https://github.com/mattermost/mattermost-plugin-jira/issues/272)
[https://github.com/mattermost/mattermost-plugin-jira/issues/277 ](https://github.com/mattermost/mattermost-plugin-jira/issues/277)
=> [MM-17750] Support Jira Server `issue_resolved` event

build/manifest/main.go, build/setup.mk, server/command.go, server/manifest.go, webapp/src/manifest.js
- It's tough to debug during development (or on customer installs) when we're not exactly sure what version and commit is running
- [MM-17809](https://mattermost.atlassian.net/browse/MM-17809)
- Would have been useful for: [MM-17794](https://mattermost.atlassian.net/browse/MM-17794)
=> [MM-17809] Include version and hash in `/jira info`

server/command.go, server/instance.go, server/kv.go, server/user.go, server/utils.go, webapp/src/actions/index.js, webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx, webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js, webapp/src/components/post_menu_actions/create_issue/create_issue.jsx, webapp/src/components/post_menu_actions/create_issue/index.js, webapp/src/hooks/hooks.js, webapp/src/reducers/index.js, webapp/src/selectors/index.js, webapp/src/utils/user_agent.jsx
This PR solves the issue of the Jira Server authentication window hanging when using the desktop app. We first determine if they are `using desktop && installed Jira Server`, then prompt the user to use the browser instead of opening the popup.
The login `redirect_to` solution does not work because the url needs to be within the supported webapp UI routes. Also, the connect url does not load in an external browser if your domain is the server's SiteURL, so that is not an option.
There is also the server-side backup connect command in case the hooks do not load properly.
https://mattermost.atlassian.net/browse/MM-17666
https://mattermost.atlassian.net/browse/MM-17699
The message is currently set to be `Please use your browser to connect to Jira.` This message only shows when they are using …
=> [MM-17666] Handle desktop app connect auth issue for Jira Server Instance

README.md
I can't find my original update to these docs. Re-updated:
- Updated webhooks configuration area for mega webhooks
- Moved manual webhook configuration to bottom 
- Updated FAQ
=> Updated instructions for Jira 2.1 plugin

webapp/src/components/post_menu_actions/create_issue/create_issue.jsx
Remove divider between normal menu items and plugin menu items on dot menu. Is now rendered in the main web app.
https://github.com/mattermost/mattermost-server/issues/11054
https://mattermost.atlassian.net/browse/MM-15943
https://github.com/mattermost/mattermost-webapp/pull/3264
=> MM-15943 remove divider above plugin menu items

server/manifest.go, server/testdata/webhook-server-comment-deleted.json, server/testdata/webhook-server-comment-updated.json, server/testdata/webhook-server-old-issue-updated-no-event-type-assigned.json, server/testdata/webhook-server-old-issue-updated-no-event-type-comment-deleted.json, server/testdata/webhook-server-old-issue-updated-no-event-type-comment-edited.json, server/testdata/webhook-server-old-issue-updated-no-event-type-commented.json, server/testdata/webhook-server-old-issue-updated-no-event-type-edited.json, server/webhook_http_test.go, server/webhook_parser.go, webapp/src/manifest.js
This PR fixes the issue of webhook payloads that do not include a `issue_event_type_name` for a `jira:issue_updated` event.
0/5 on keeping this release small and including just this commit here. I'd like to get this out quick as it's causing Jira servers with older versions to not work with the plugin (legacy webhooks and channel subscriptions).
Here's all of the new commits on master since 2.1 release: https://github.com/mattermost/mattermost-plugin-jira/compare/fdba0d10e3da8e1171d26d2f7dbc1021e41b31f2...master in case the team thinks we should include another fix in the patch.
https://mattermost.atlassian.net/browse/MM-17682
https://mattermost.atlassian.net/browse/MM-17750
https://github.com/mattermost/mattermost-plugin-jira/issues/277 …
=> Include missing event type name fix (#287) for patch release

webapp/src/hooks/hooks.js
Normally the Jira Cloud connect popup works with the Desktop App, but after changes in the v4.3 of the Desktop App, it longer works. Nothing happens when you run `/jira connect`. Until we have a more sound solution, we will mimic the behavior we have for Jira Server in order to avoid connect issues.
https://mattermost.atlassian.net/browse/MM-19144
=> [MM-19144] Prompt user to use browser to connect to Jira Cloud

server/issue_parser.go, server/webhook.go, server/webhook_jira.go
The Issue.Self URLs in Jira Cloud webhooks appear to have become invalid.
This PR stops relying on them.
=> Fixed MM-19213: Issue.Self is no longer good

server/testdata/webhook-cloud-comment-deleted.json, server/webhook_http_test.go, server/webhook_parser.go
The `comment_deleted` webhook events for Jira Cloud no longer have the user's key in the `updateAuthor` object. This PR adds a check for the `accountId` if the k ey is not present.
https://mattermost.atlassian.net/browse/MM-19201
=> [MM-19201] Check for accountid on updateAuthor for Jira Cloud

webapp/src/components/react_select_setting.jsx
This PR fixes an issue where adding or deleting a Jira project from your Jira instance may not be reflected in the subscribe modal, until you open it twice.
https://mattermost.atlassian.net/browse/MM-19179
I believe this is caused by React reusing the same component that was used the last time the modal was open. We fetch new metadata, and feed a new array of options to the AsyncSelect component. But it assumes that it should reuse the same AsyncSelect component, causing the updated options prop to be ignored (as expected).
In a previous PR https://github.com/mattermost/mattermost-plugin-jira/pull/318 we made it so the only condition that would cause the AsyncSelect component to be used, is if we pass a `limitOptions` prop. Since there can apparently be some component references carried …
=> [MM-19179] Avoid react-select caching when num options is negligible

webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx, webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
This PR adds the `Delete` button to the Subscriptions modal, but disables the button unless the subscription has been previously saved.
Previously, the `Delete` button was hidden.
This image capture shows a previously saved subscription being edited.  You can observe that the `Delete` button is now active, allowing the user to delete the subscription
https://mattermost.atlassian.net/browse/MM-18076
=> [MM-18076] Add disable button to create subscriptions modal

webapp/src/hooks/hooks.js
This reverts PR https://github.com/mattermost/mattermost-plugin-jira/pull/332 "Prompt user to use browser to connect to Jira Cloud"
There was an issue with opening popups in the desktop app for v4.3, which seems to be solved by https://github.com/mattermost/desktop/pull/1062 .
~Though, running the desktop app on master locally shows that the issue here is not fixed for me. @deanwhillier Can you weigh in on this?~
Edit: Nevermind I wasn't running the latest desktop build. The issue is fixed.
https://mattermost.atlassian.net/browse/MM-19144
=> Revert "Prompt user to use browser to connect to Jira Cloud"

webapp/src/components/confirm_modal.tsx, webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/edit_channel_settings.test.tsx, webapp/src/components/modals/channel_settings/edit_channel_settings.tsx, webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
This PR adds a confirm modal that gets called when the user clicks the 'Delete` button on a subscription.  This is an added step to reduce the chance of an accidental subscription deletion.
There are two area where a user can delete a subscription.
1) From the Subscriptions List Modal.  This view shows saved subscriptions with an inline delete button for each subscription
Corresponding Confirm Modal for this case:
2) After a subscription is saved and a user clicks the `Edit` button on a subscription.
Corresponding Confirm Modal for this case: 
Other Notables for this ticket:
* the confirm modal was copied from the webapp repo, and converted to Typescript
* `zIndex` is set to 2001. This brings the modal in front of the full-screen modal. …
=> [MM-18736] Add Confirm Modal for Subscription Delete Button Click

server/command.go, server/subscribe.go, server/subscribe_test.go, webapp/src/hooks/hooks.js
This PR adds functionality to list out subscriptions of all channels. It is only accessible to sys admins.
https://mattermost.atlassian.net/browse/MM-18536
Example Output:
```
~some-channel-name (2):
* PROJ1 - Subscription X
* PROJ1 - Subscription Y
~some-other-channel-name (1):
* PROJ2 - Subscription Z
```
The channels name are converted to markdown, and so they are clickable links to the channel.
=> [MM-18536] `/jira subscribe list` command

server/http_test.go, server/subscribe.go, webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
This PR makes it so the user can only have 100 characters in their subscription name.
https://mattermost.atlassian.net/browse/MM-19643
This is adding validation server-side and client-side. I don't expect users to be using our API without the UI, but the server should be performing its own validation for data integrity.
=> [MM-19643] Limit Subscription name to 100 characters

webapp/src/components/modals/channel_settings/channel_settings_modal.scss, webapp/src/components/modals/full_screen_modal/full_screen_modal.jsx, webapp/src/components/modals/full_screen_modal/full_screen_modal.scss
This PR makes the header of the full screen modal (part containing the close button) have a height of 50px to make it so the "Create Subscription" button is below the x when the screen is narrow.
https://mattermost.atlassian.net/browse/MM-19685
Before
After
=> [MM-19865] Fix modal close button to not overlap when screen is narrow

server/http_test.go, server/subscribe.go
This PR adds a post, from the Jira Bot, informing users when a subscription was created, edited or deleted.
https://mattermost.atlassian.net/browse/MM-18674
=> [MM-18674] Add post in channel when subscription is created or updated

webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/channel_settings.tsx
When a user that does not have permissions to create channel subscriptions opens the modal, they are now shown the text:
> You do not have permission to edit the subscriptions for this channel. Configuring a Jira subscription will create notifications in this channel when certain events happen in Jira, such as an issue being updated or created with a specific label. Speak to your Mattermost administrator to request access to this functionality.
https://mattermost.atlassian.net/browse/MM-19793
=> [MM-19793] Change wording of channel subscriptions permissions error

webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/edit_channel_settings.tsx, webapp/src/testdata/cloud-get-create-issue-metadata-for-project-many-fields.json, webapp/src/utils/jira_issue_metadata.tsx
When parsing fields for filters, the dataset includes default fields. Some code was reused for events, and the default fields are already included inside of the component for events. This PR makes it so, for events, only custom fields are retrieved from the issue metadata.
https://mattermost.atlassian.net/browse/MM-19810
=> [MM-19810] Handle default vs custom fields in events

webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap, webapp/src/components/jira_epic_selector/jira_epic_selector.tsx, webapp/src/components/modals/channel_settings/channel_settings_filter.tsx
This PR removes the X that is used to clear all of the values in a given filter's select dropdown. Now you cannot accidentally remove the values all at once.
https://mattermost.atlassian.net/browse/MM-20185
Before
After
=> MM-20185 - Make subscription filter values not clearable

server/issue.go, webapp/src/components/jira_epic_selector/jira_epic_selector.test.tsx, webapp/src/components/jira_epic_selector/jira_epic_selector.tsx
This PR improves the search for Epics by using `*` in an additional clause.
`... and "Epic Name"~"{searchTerm}"`
becomes
`... and ("Epic Name” ~ “{searchTerm}” or “Epic Name” ~ “{searchTerm}*”)`
When not using the clause with `*`, searches with just a few characters do not find many results. Using two clauses together:
- `~` makes it so the fuzzy search for several words works
- `~...*` makes it so exact prefix matching works
https://mattermost.atlassian.net/browse/MM-20013
=> [MM-20013] Improve epic link search

webapp/src/components/modals/channel_settings/__snapshots__/channel_settings_filter.test.tsx.snap
[This PR's](https://github.com/mattermost/mattermost-plugin-jira/pull/380) changes introduced a one-line change in a snapshot. But the PR was not completely in-sync with master so the snapshot change was not registered before the merge.
=> Fix snapshot after MM-20013 PR merge

webapp/.eslintrc.json, webapp/src/actions/index.js, webapp/src/components/modals/channel_settings/channel_settings.test.tsx, webapp/src/components/modals/channel_settings/channel_settings.tsx, webapp/src/components/modals/channel_settings/index.ts, webapp/src/components/modals/channel_settings/shared_props.ts, webapp/src/hooks/hooks.js, webapp/src/reducers/index.js
When the `get-jira-project-metadata` call fails, we should show an error to the user.
https://mattermost.atlassian.net/browse/MM-20014
https://mattermost.atlassian.net/browse/MM-19928
The modal does not open, and an ephemeral message is posted:
Permissions error
Error fetching Jira project data
=> [MM-20014] Show project metadata fetch error

server/command.go, server/subscribe.go, server/subscribe_test.go
This PR improves the output of the `/jira subscribe list` command output by grouping channel subscriptions by team.  For DM and GM channels, post the hashes under the Generic Headline "Group and Direct Messages".
The following is directly from the commit logs, but is a comprehensive list of the changes made and testing needed for QA.
Group channels by Team Name
Include Group and Direct Message channels exposing hashes for channel names
Add tests for the following:
- team and DM/GM channels subscriptions
- team only channel subscriptions
- DM/GM only channel subscriptions
- Team Heading level and bold of channel names
- Subscription that was not previously saved with a name
- Zero subscriptions on any channels
- Team names are sorted alphabetically …
=> [MM-19689] Improve `/jira subscribe list` UX

server/issue.go, server/issue_test.go, server/kv_mock_test.go
- Instead of just looking for a matching lowercase substring the `transitionJiraIssue` method will now remove any whitespace before lowercasing both strings and then look for a matching substring
- This allows the user to type `/jira transition issue inp` to match the `In Progress` state
- Tested by building the plugin locally and ensuring the expected behaviour occurs
Fixes: https://github.com/mattermost/mattermost-plugin-jira/issues/337
=> Ignore whitespace when matching potential transition state 

server/command.go
**Summary**
This PR will 
- Show different instructions to end-users vs sysadmins for `/jira help` command
- Show command `/jira subscribe list` for admins in `/jira help` output. It is currently not in the help text.
Fixes: https://github.com/mattermost/mattermost-plugin-jira/issues/391
=> GH-391: Show different instructions to end-users vs sysadmins for `/jira help` command

webapp/src/components/modals/full_screen_modal/full_screen_modal.scss
The css adjustments for the two buttons were accidentally removed here
https://github.com/mattermost/mattermost-plugin-jira/commit/ad3cc4c2581e73c91a9fa520a4ec7a8299a4e0b3#diff-0f8116c7c9b5c1bb6abab32cd1b3cd5f
https://mattermost.atlassian.net/browse/MM-20940
=> [MM-20940] Reintroduce css for back and close buttons for full screen modal

webapp/src/action_types/index.js, webapp/src/actions/index.js, webapp/src/hooks/hooks.js, webapp/src/plugin.tsx, webapp/src/reducers/index.js, webapp/src/selectors/index.js
When the `Allow users to attach and create Jira issues in Mattermost` config var is set to false, the webapp portion of the plugin was not being initialized in general. This can cause problems with `/jira subscribe` and `/jira connect`.
This PR makes it so only the "create" and "attach" features are disabled as noted in the config.
https://mattermost.atlassian.net/browse/MM-20738
Here is the relevant setting in the config:
With `Allow users to attach and create Jira issues in Mattermost` set to true:
- `/jira subscribe` should work
- `/jira create` should work
- Both post dot menu actions for create and attach should appear
With `Allow users to attach and create Jira issues in Mattermost` set to false:
- `/jira subscribe` should work
- `/jira create` should not work
- Neither post dot …
=> [MM-20738] When Jira UI config var is set to false, initialize webapp except for create and attach

webapp/src/components/icon.tsx
Needs to go in for jira 2.3.
Fixes the alignment for the icons.
This class should be used now as a wrapper for all plugins that introduce icon in the menu dropdown.
=> Updating jira icon alignment in menu

server/subscribe.go
When reviewing the task "Make access to KV store atomically safe when saving/removing subscriptions" https://github.com/mattermost/mattermost-plugin-github/issues/141#issuecomment-547648457, it was discovered that there is a potential bug with the `atomicModify` function in the Jira plugin, leftover from  a change of which plugin API method is used. There is more context in the linked comment.
The `success` value returned from `API.KVCompareAndSet` is overwritten with a hardcoded boolean. Using the value returned from `KVCompareAndSet` seems to be the correct method here.
https://mattermost.atlassian.net/browse/MM-21054
An issue occurred on community, where an existing subscription failed to save because of an error `modification error: Existing subscription does not exist`. This error …
=> [MM-21054] Remove hardcoded boolean in atomicModify

server/stats.go
The hostnames on community-daily and community-release proved to be too long for the key to be included directly. Hashing them now.
Fixes https://mattermost.atlassian.net/browse/MM-20928
=> MM-20928 Fixed hostname too long in stats key

server/testdata/webhook-issue-updated-reopened-one-changelog.json, server/testdata/webhook-issue-updated-resolved-one-changelog.json, server/testdata/webhook-server-issue-updated-commented-3.json, server/webhook_http_test.go, server/webhook_parser.go, server/webhook_parser_misc_test.go
Added bold to some verbs. 
In the case of a reopened and resolved ticket, if there are more than one changelog, the text is "updated" to I didn't make it bold.
https://github.com/mattermost/mattermost-plugin-jira/issues/168
=> [GH-168] Bold action verb in webhook notification pretext

webapp/src/hooks/hooks.js, webapp/src/plugin.tsx
This PR fixes an issue where the plugin's reducers were not being initialized until after the plugin settings were fetched, causing the `RECEIVED_PLUGIN_SETTINGS` action to not be processed. There is also a backup for supplying the fetched settings to the Hooks constructor directly.
https://mattermost.atlassian.net/browse/MM-21189
=> [MM-21189] Fix plugin reducer initialization

server/event_types.go, server/issue.go, server/subscribe_test.go, server/testdata/webhook-issue-updated-components.json, server/webhook_parser.go, webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/edit_channel_settings.tsx, webapp/src/utils/jira_issue_metadata.tsx
This PR adds support for the `Components` Jira field. It is now accessible as a subscription event type and field filter.
https://mattermost.atlassian.net/browse/MM-19170
https://github.com/mattermost/mattermost-plugin-jira/issues/338
=> [MM-19170] Add support for "Components" Jira field

server/subscribe_test.go
This particular test was testing against the exact returned value, which is not fully deterministic.  The issue is that while the teams are sorted, the channel names are not.  Looking at the previously checked in test, `Team 2` has two channels.  The returned order of these two channels is non-deterministic.  This PR changes the test to use a Regex which allows testing for the team name sorting, and channel name existence, without reliance on non-deterministic channel name ordering.
https://mattermost.atlassian.net/browse/MM-21350
=> [MM-21350] Fix flaky jira subscribe test

go.mod, go.sum
- We're now using the up-to-date oauth2 package because they fixed the jira `accountid` problem. 
- Also changed the MM server 5.12 dependency so that it works with go 1.13 (it was breaking on my machine)
- QA review: need to make sure this doesn't break the cloud oauth2 system (I tested it, and it works for me, but just in case).
- Fixes #398 
- [MM-21295](https://mattermost.atlassian.net/browse/MM-21295)
=> Remove workaround in go.mod

plugin.json, server/command.go, server/plugin.go
…with the output of  command
In system console, jira admin can specify extra help-text to be shown along with the output of command /jira help.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/392
=> GH-392: Allow system admins to provide a block of text to display in output of `/jira help`

webapp/src/components/modals/channel_settings/select_channel_subscription.tsx
This PR adds placeholder text when a user tries to select a subscription but none exist.
Fixes #426
=> [MM-21218] Display placeholder text when a channel has no subscriptions

server/command.go, server/command_test.go, server/utils/utils.go, server/utils/utils_test.go
If Jira instance is being installed as a server instance but the URL looks like a Jira Cloud URL, return a friendly error message with a hint.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/425
=> MM-16948 Check if Jira server url actually is a Jira Cloud URL

webapp/src/components/modals/channel_settings/__snapshots__/edit_channel_settings.test.tsx.snap, webapp/src/components/modals/channel_settings/edit_channel_settings.tsx
**Summary**
MM-20281 - Show channel name at the top of subscription modal when editing a subscription 
[https://mattermost.atlassian.net/browse/MM-20281](https://mattermost.atlassian.net/browse/MM-20281)
Fixes #424
=> [MM-20281] Show channel name at the top of subscription modal when editing a subscription

server/http_test.go, server/issue_test.go, server/subscribe.go
This PR validates the create/update subscription form. The subscription, project chosen, events chosen, and issue types chosen must be valid.
The bulk of the test changes are due to the validation of issue types. The subscriptions provided for the tests did not have issue types assigned.
https://mattermost.atlassian.net/browse/MM-17903
=> [MM-17903] Validate form for subscription create/edit

go.mod
This ticket bumps the go version.
The bump was initially a request to adjust the `mattermost-server` references to `/v5`.  Looking into the imports, I did not see any references other than `/v5`
I used the following to extract any `mattermost-server` imports.
`rg mattermost-server | grep -v 'mattermost-server/v5'`
https://github.com/mattermost/mattermost-plugin-jira/issues/452
=> bump go version from 1.12 to 1.13

server/http.go, server/issue.go, webapp/src/actions/index.js, webapp/src/components/jira_epic_selector/__snapshots__/jira_epic_selector.test.tsx.snap, webapp/src/components/jira_epic_selector/index.ts, webapp/src/components/jira_epic_selector/jira_epic_selector.test.tsx, webapp/src/components/jira_epic_selector/jira_epic_selector.tsx, webapp/src/components/jira_issue_selector/index.js, webapp/src/components/jira_issue_selector/jira_issue_selector.jsx, webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
This PR refactors the issue search endpoint to be more flexible, so the epic search can use the same endpoint. This is useful to allow for more help wanted tickets centered around searching for issues.
https://mattermost.atlassian.net/browse/MM-21762
=> [MM-21762] Refactor jira issue search

server/issue_parser.go
**Summary**
MM-20280-Display reporter name and avatar in `/jira view` output
[https://mattermost.atlassian.net/browse/MM-20280](https://mattermost.atlassian.net/browse/MM-20280)
Fixes #421
=> [MM-20280] Display reporter name and avatar in `/jira view` output

server/command.go, server/issue.go
This PR adds the `/jira unassign` slash command.
A) When successful, the command does two things:
Unassigned Jira issue <issueKey>
B) The following is a list of error cases and the returned ephemeral message. The ephemeral message should have the same profile picture and username as other messages posted by the Jira plugin.
https://github.com/mattermost/mattermost-plugin-jira/issues/92
=> Add unassign slash command

server/client.go
**Summary**
[MM-17816] Reporter is not automatically set for `/jira create` on Jira Server, when required field is missing
[https://mattermost.atlassian.net/browse/MM-19256](https://mattermost.atlassian.net/browse/MM-19256)
Fixes #393  
[MM-17816]: https://mattermost.atlassian.net/browse/MM-17816
=> [MM-17816] Reporter is not automatically set for `/jira create` on Jira Server, when required field is missing

server/webhook.go
=> Generate a proper webhook URL

server/webhook_http_test.go, server/webhook_parser.go, server/webhook_parser_misc_test.go
This PR changes webhook handling for events of type "issue commented" and "issue comment edited" in order to render them as quoted messages in Mattermost.
Thanks for reviewing!
Before
After
Before
After
Fixes #167.
=> [GH-167] Render JIRA webhook comments as quoted messages

server/command_test.go, server/http.go, server/issue.go, server/issue_test.go, server/kv_mock_test.go, server/plugin.go, server/user.go, server/user_test.go
**Summary**
Created/Attached to a Jira issue message should include a reference to the Jira plugin
Fixes #438
=> Created/Attached to a Jira issue message should include a reference to the Jira plugin

go.mod, go.sum, server/http.go, server/instance_cloud.go, server/issue.go, server/plugin.go
Support for creating tickets with workflows. Example action that creates a JIRA ticket as the plugin.:
```json
{
"name": "MakeTicket",
"type": "jira_create",
"user_id": "",
"fields": {
"project": {
"key": "EXT"
},
"issuetype": {
"name": "Bug"
},
"summary": "This is a test ticket from workflow {{.Instance.Number}}",
"description": "Message: {{.Trigger.TestTrigger.Message}}"
}
}
```
Creating tickets as the plugin only works on JIRA cloud. Creating tickets as the user should work on both. 
Requires: https://github.com/mattermost/mattermost-plugin-workflow/pull/71
=> MM-22063 Adding create ticket action support for workflow.

.gitignore, .vscode/settings.json, plugin.json
Fixes #477 
Replaced old link with `https://github.com/mattermost/mattermost-plugin-jira/blob/master/readme.md`
=> Fix dead link

server/command.go, server/command_test.go, server/instance.go, server/instance_cloud.go, server/instance_server.go, server/kv_mock_test.go
This PR links the appropriate Jira settings page after `uninstall cloud|server` is successful. I took the liberty to perform some refactoring so only one function is used to perform the uninstall.
I have also added a test with basic cases. My original intent was to have more tests but I am not sure about the best way to setup a test for the `uninstall` command.
Thanks for reviewing!
Fixes #145.
=> [GH-145] Add link to ephemeral message after uninstall

plugin.json, server/plugin.go, server/webhook.go
Added a config option to drop issue description and comment bodies from webhook and subscription posts. They should continue displaying in DMs and ephemeral posts without changes.
Fixes https://mattermost.atlassian.net/browse/MM-21696
Config: 
Hide ON:
Hide OFF (default) as before,
=> MM-21696: New config setting: Hide issue descriptions and comments

server/atlassian_connect.go, server/http.go, server/instance.go, server/instance_cloud.go, server/instance_server.go, server/issue.go, server/stats.go, server/subscribe.go, server/user.go, server/user_cloud.go, server/user_server.go, server/webhook_http.go
There was some funky error handling in http functions, streamlined it, should now consistently use `respondErr` when returning errors in http handlers.
Fixes https://mattermost.atlassian.net/browse/MM-19674
=> MM-19674: use respondXXX in http handlers

server/issue.go, server/issue_test.go, server/utils.go
The most recent commit is causing a build error because function `respondErr` exists twice.
The two function signatures are below:
```go
// server/issue.go
func respondErr(w http.ResponseWriter, code int, err error) (int, error) {}
//server/http.go
func respondErr(plugin *Plugin, status int, e error, mmuserID, jiraBotID, channelID, message string) (int, error) {}
```
I've added my suggestion for renaming the function in `issue.go` and chose to rename this function because it is used in fewer locations.
The suggestion is `s/responseErr/respondEphemeralErr/` because this response is specifically sending an ephemeral post.
These are the commits that are causing the build failure.
`issue.go` - https://github.com/mattermost/mattermost-plugin-jira/pull/454/files
`http.go` - …
=> rename `respondErr` function

webapp/package-lock.json, webapp/package.json
The following PR (https://github.com/mattermost/mattermost-plugin-jira/pull/512) was originally created to update npm packages but has also broken the build.  This is a fresh PR to update off of the latest master build.
The command that has been run is `npm -E audit fix` which updates security issues.  
`-E` is short for `--save-exact`
=> npm -E audit fix in prep for 2.4 release

server/command.go
*Problem*
jiraCommandHandler contains the mappings of slash commands to their corresponding command handler functions. The following slash commands are missing and should be added to the HelpText variables.
*Resolution*
Mapped the following commands with their descriptions to the handler functions. 
webhook
stats
info
help
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/485
=> [MM-485] - Update `commonHelpText` and `sysAdminHelpText` to include all slash commands

server/command.go
This PR removes the extra `/` from the connect URL indicated in `/jira info` output when a Jira instance is not yet connected. That seems to be the only place where this URL is constructed so I thought adding new method on `Plugin` wouldn't be necessary.
Alternative solution: `strings.TrimLeft` on `routeUserConnect`.
Fixes #490
=> [GH-490] Fix connect link on /jira info output

server/plugin.go
This PR improves the generation of the plugin key by making it a bit more deterministic.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/532
@levb This wasn't occurring for you because your ngrok URL is less than 22 chars long. The issue is occurring with URLs that are between 22 and 29 chars long.
=> Refactor plugin key generation code

plugin.json, server/manifest.go, webapp/src/manifest.ts
Bump version to v2.4.0
Proposal to bump version following Release Notes:
Bump version to v2.4.0
Proposal to bump Feature Version to prep for release with the following Release Notes:
* 6c581ee Bump version to 2.4.0
* 0a6a9f5 [GH-506] Correctly link or embed attachments (#517)
* 3dea771 Add docker-compose.yml to spin up Jira Server instance (#516)
* 5c00b4f rename `respondErr` function (#513)
* ab82ff2 Add CODEOWNERS and maintainers (#518)
* 09711c0 MM-19674: use respondXXX in http handlers (#500)
* cbd6876 [MM-17816] Add the ability to transition an issue after running `/jira view` (#454)
* b2fb81f MM-21696: New config setting: Hide issue descriptions and comments (#503)
* d1c74e3 Add Site URL to third-party cookie error message (#478)
* 2b7d074 [GH-145] Add link to ephemeral message …
=> Bump version to 2.4.0

readme.md
This PR is the proposal to add additional badges to the github repo.
The proposal is to add the following:
You can view the file, with changes [here](https://github.com/mattermost/mattermost-plugin-jira/blob/add-badges-to-readme/readme.md)
n/a
=> Add badges to README

webapp/src/components/jira_issue_selector/jira_issue_selector.jsx
This PR remove the help text from the attach message to issue modal. 
Before:
After:
#561
=> [GH-561] Remove invalid help text on Jira Attach search box

server/issue.go
remove "by mattermost-jira-plugin" trailer to create and attach messages.  This was discussed at length in the issue ticket and determined too confusing for some users.
Fixes #551
=> Remove `by mattermost-jira-plugin` link/text

server/issue.go, server/issue_test.go
Attachment text not shown if error occurs while adding attachment.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/529
=> [GH-529] No attachment text when error happens while uploading attachment

readme.md
Fixes the TOC in the README so all links work and take the user to the anchored headers
Fixes #527
=> [GH-527] Fix README TOC anchor linking

server/issue_parser.go
In the case that a `transition name` does not match the `to state` in the slack attachment options picker, the user would receive an error such as below:
Note that `Start Progress` in this case is the `transition name` and the list `In Progress, Solved, Close` are the states.
`2020-05-26T13:45:03.351+0200    error   mlog/sugar.go:23        ERROR:  {"plugin_id": "jira", "Status": "500", "Error": "\"Start Progress\" is not a valid state. Please use one of: \"In Progress, Solved, Closed\"", "Host": "", "RequestURI": "", "Method": "POST", "query": ""}`
To fix this, the options picker value needs to be the state name, not the transition name.  The current modification will show the transition name in the picker, but the underlying value will be the `to state`
I modified my jira testing …
=> [GH-549] fix transition slack attachment transition

server/kv.go
Fixes #588 
My best guess is that the credentials expired (after 15 minutes), improved the error message
=> Fixed handling expired credentials

readme.md, server/command.go, server/command_test.go
Summary
Problem
When configuring webhooks, in Jira, the SITEURL must use **https**:// if connecting to a cloud instance. This ticket has two requests.
Document in the README that cloud instances will require an https endpoint.
Add validation that will reject non-https URLS for jira cloud instances. This will be handled in the code that is executed with /jira install cloud <URL>
Resolution
Validate non secure http protocol command line for cloud install.  Present user with correct command line.
Update readme file with secure protocol requirement (HTTPS)
Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/487
=> Validate https secure protocol for jira cloud install.

server/testdata/webhook-issue-comment-created-indentation.json, server/webhook_http_test.go, server/webhook_parser.go
This pull request indents all the text of a post for a jira comment that has line breaks.
https://github.com/mattermost/mattermost-plugin-jira/issues/491
=> [GH-491] Fix posts for jira comments indenting a quote text that has line breaks

plugin.json, server/command.go, server/command_test.go, webapp/src/components/form_button.jsx
jira plugin config UI changed and `/jira webhook` added there
jira webhook URL added in outputs of `/jira install` and `/jira uninstall`
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/531
=> GH-531 Add info about /jira webhook

webapp/src/selectors/index.js
We've applied this fix for a different plugin but did not apply it here. If the SiteURL is not set, the code was making the API calls go to `//plugins/jira`. Now it will use `/plugins/jira`.
=> Avoid double slash in webapp API calls when SiteURL is not present

Makefile, build/custom.mk, server/utils/telemetry/rudder.go
Allow setting rudderWriteKey during build time.
I used the following as references:
https://github.com/mattermost/mattermost-plugin-zoom/pull/148
https://github.com/mattermost/mattermost-plugin-todo/pull/101
https://github.com/mattermost/mattermost-plugin-mscalendar/pull/152
fixes #612
=> [GH-612] Add ability to change telemetry key to production key on release builds

server/plugin.go
If the `EnableDiagnostics` config value is false, it is read as a nil pointer at runtime. This causes the plugin to panic during activation.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/636
=> Check for nil diagnostic setting

webapp/src/components/modals/create_issue/create_issue_form.tsx
There was a regression on the Create Issue modal staying open when the user has required fields not covered in the form submission. This PR makes sure the modal closes when this scenario occurs.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/638
=> Close modal on missing required fields

plugin.json, server/manifest.go, webapp/src/manifest.ts
Bump version to `v3.0.0-beta2.1`
The previously released `v3.0.0-beta2` had a critical bug that needed to be fixed.  `v3.0.0-beta2` was also removed from the releases.
This bump includes the bug fix #641 and will be release post merging this ticket.
#647
=> Bump version to v3.0.0-beta2.1

server/command.go
Currently when you run `/jira disconnect` when:
- There is more than one instance installed
- and the user is not connected to any instance
This is the output of the command:
> Could not complete the disconnection request. You do not currently have a Jira account at "" linked to your Mattermost account.your account is not connected to Jira. Please use `/jira connect`: not found
We can instead have just this portion if the user does not provide a jira URL in their request:
> Your account is not connected to Jira. Please use `/jira connect` to connect your account.
Otherwise the error will read as:
> You do not currently have a Jira account at (JIRA URL) linked to your Mattermost account. Please use `/jira connect` to connect your account.
Fixes …
=> Improve disconnect message when user is not connected to any instances

webapp/src/reducers/index.js
The `defaultUserInstanceID` reducer was returning `undefined`. This means `action.data.user` was defined, but `action.data.user.default_instance_id` was not present. This PR protects against this so no error happens.
I'm not sure why the websocket message on community has an entirely different structure for the `user` property in the following websocket messages:
Correct websocket message I see locally
```json
{
"event": "custom_jira_connect",
"data": {
"can_connect": false,
"instances": [
{
"instance_id": "http://localhost:8080",
"type": "server"
},
{
"instance_id": "https://mmtest.atlassian.net",
"type": "cloud"
},
{
"instance_id": "http://dkh-jira.ngrok.io",
"type": "server"
}
],
"is_connected": true,
"user": {
"connected_instances": [
{
"instance_id": "http://localhost:8080",
"type": …
```
=> Avoid defaultUserInstanceID reducer error

webapp/src/components/modals/channel_settings/channel_settings.test.tsx, webapp/src/components/modals/channel_settings/channel_settings.tsx, webapp/src/components/modals/channel_settings/channel_settings_internal.tsx
This PR reverts some behavior changed when implementing the multi-server subscription modal. The old behavior is better UX for users that do not have subscribe permissions, and since we are showing the command to all users, I think this case should be a good experience.
https://github.com/mattermost/mattermost-plugin-jira/issues/620
During the multi-server implementation, how we fetch subscriptions changed slightly. This resulted in a change of how the user is shown that they don't have permissions to edit subscriptions.
Previous functionality:
- User runs `/jira subscribe`
- Ephemeral message shows `Fetching subscriptions.` Permission checks begin
- If permissions valid, show modal and show data
- If permissions not valid, do not show modal, and show error in ephemeral message
Before …
=> Delay opening subscribe modal until we know the user has permissions

server/user_cloud.go
Currently if a user tries to connect to a Jira Cloud instance, we use the Atlassian Connect authentication method. This no longer works with Chrome, due to browser security updates, and will start failing on other browser platforms as well.
We will provide an alternative form of authentication, but for the time being (3.0 release), we should show a disclaimer if the user is using Chrome to use a different browser.
Current text:
> Mattermost failed to recognize your user account. Please make sure third-party cookies are not disabled in your browser settings. Make sure you are signed into Mattermost on (MM URL).
Proposed text to add to the end:
> Chrome is currently experiencing an issue with this authentication method. If you are using Chrome, please try using a different browser to …
=> Include chrome-specific error message in third-party cookie connect error

plugin.json
Update message to inform users that only instances installed v2.4 or earlier apply to Jira Groups
#645
=> [GH-645] update text to mention groups only work for legacy instance

server/command.go, server/jiraTracker/tracker.go, server/kv.go, server/kv_migrate_test.go, server/kv_mock_test.go
This PR adds a `/jira v2revert` slash command and also telemetry tracking for when the command is used.
The plugin key `known_jira_instances` is generated by iterating through the `v3/instances` objects and extracting the `ID` (URL) and `type` (Ex `{http://some.jira.com: cloud}`)
The V3 user keys, of the form `user_xxx` are left in the database after `v2revert` is run. I'm 0/5 if we decide to remove them.  
**Some checks were made to help ensure the command is not run unintentionally:**
- If no V2Legacy instances, this is a fresh v3.0.  Don’t allow them to v2revert.  The following message is returned to the user.
`No Jira V2 legacy instances found.  V3 to V2 Jira migrations are only allowed when the Jira plugin has been previously migrated from a V2 version.`
- use `--force` is required …
=> Implement `/jira v2revert`

assets/templates/command/install_server.md
We have had several customers have this issue.  The solution is actually simple and doesn't require any code changes. Please see this comment in the issue for an understanding of what caused the issue.
As a solution, I have changed the output of the `/jira instance install server example.com` command.  
To help clarify what must be done for each jira input form, I have consolidated the previous bullet 5 into bullet 4.  Now each numbered bullet, 3, 4, and 5 list the instructions for each input form.  I also think the previous bullet 5 with the **IMPORTANT** text is overkill and was causing extra distraction.
#526
=> [GH-526] make server install help text more clear to the user.

webapp/src/components/jira_instance_and_project_selector/jira_instance_and_project_selector.tsx
Thsi ticket resolves the case where a saved subscription is edited.  Previously, the `default_project_key` was getting set when the edit subscription modal would open. This resulted in opening a saved subscription with a different project that the saved default project would get changed to the default project key.  
The resolution is to check if the selectedProjectID exists, which is the saved subscription project ID.
#663
=> [GH-663] Saved subscription project value incorrectly updated to default_project_key value

server/command_test.go, server/http_test.go, server/issue_test.go, server/mock.go, server/plugin_test.go, server/user_test.go, server/webhook_http_test.go
- Add function for batch calls to mock.AnythingOfTypeArgument
- Substitute calls to mock.AnythingOfTypeArgument to a new function
Closes #590
=> Add batch method to call to mock.AnythingOfTypeArgument

server/command.go
This PR fixes a printing issue when an instance is a legacy instance
#672
=> [GH-672] add additional pipe for v2legacy print lines

server/command.go, server/instances.go
When showing the list of available `--instance` options, show the aliases if available, else show the `instanceID`.
I tested this with 
`/jira issue view JTP-1`
`/jira issue view jstp-1 --instance server-alias`
`/jira issue view jtp-1 --instance https://mmtest.atlassian.net`
`/jira assign jstp-1 jfrerich --instance server-alias `
/jira assign jtp-1 jfrerich --instance https://mmtest.atlassian.net 
Fixes #678
=> [GH-678] when using --instance, show alias if available else show the instanceID

plugin.json
Upgrading min_server_version to 5.26.0 so that autocomplete functions correctly.  Dylan found an issue with 5.24 where `/jira connect` gets replicated by the number of instances installed.
N/A
=> Bump min server version to v5.26.0

server/plugin.go
Change log level for autolink when no cloud instance. From WARN to INFO.
Fixes #589
=> [GH-589] Change log level for autolink when no cloud instance

docs/admininstrator-guide/notification-management.md, docs/development/environment.md, readme.md
Some development docs that were in the README got lost when switching over to GitBook. This PR brings those docs to GitBook, and links to them from the README.
=> Relocate dev docs to GitBook

server/plugin.go
This PR fixes a bug I stumbled upon when I was trying to reproduce #676 against the current `master`. That bug was causing the plug-in to crash due to the wrong error object being called during the warning log of autolink plug-in checks. Here I'm only making sure that the correct error object is used and only if it is not `nil`. More details can be found on the issue itself.
Thanks @mickmister for helping me with the troubleshooting.
Fixes #708
=> [GH-708] Fix check for autolink plug-in errors

webapp/src/actions/index.ts
This PR sends an ephemeral message to the user after the `/jira connect` flow is completed. Please check [this comment](https://github.com/mattermost/mattermost-plugin-jira/issues/149#issuecomment-716924011) regarding this issue, as this PR does not address all the requirements.
GH-149
=> [GH-149] Send ephemeral message after /jira connect flow succeeds

server/command.go, server/info.go, server/instances.go, server/user.go
There is an issue where we update user info in the kv store, and immediately try to read the info, resulting in a data inconsistency.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/694
=> Add *User param to GetUserInfo to avoid read replica issue

plugin.json, server/manifest.go, webapp/src/manifest.ts
This release contains the following PRs on top of 3.0:
- https://github.com/mattermost/mattermost-plugin-jira/pull/660
- https://github.com/mattermost/mattermost-plugin-jira/pull/723
See https://github.com/mattermost/mattermost-plugin-jira/pull/735
=> Bump version to 3.0.1

server/atlassian_connect.go, server/plugin.go
This PR makes it so the Jira Cloud instance install does not fail when the autolinks register fails. It's still unknown why the Jira Cloud bot account cannot fetch the project keys, but this is at least a fix for the bug of stopping the instance install when that happens.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/758
=> Let Jira cloud install finish when autolink fails

server/command.go
This PR fixes the `/jira webhook` output to point to the docs to explain legacy webhooks, rather than showing a bunch of likely unnecessary information about legacy webhooks.
These docs need to be merged first: https://github.com/mattermost/mattermost-plugin-jira/pull/754. Edit: the docs PR is merged now
Fixes https://mattermost.atlassian.net/browse/MM-34684
=> [MM-34684] Fix '/jira webhook' text that explains legacy webhooks

server/webhook_parser.go
This PR fixes an issue where Jira Cloud users are not receiving DM notifications for being the assignee of an issue.
The issue was that we were first checking if the `Name` of the assignee matched the comment author, but we were not checking if these values were empty. On Jira Cloud, both values are always empty, so they were always equal, so the condition was always true.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/479
Note that the assignee will only receive notifications for *comments* on the issue. There is no functionality in the plugin that makes it so the assignee gets a notification for updating the epic for instance.
=> Fix assignee comment notification for Jira Cloud

server/subscribe.go
Do not return an error if a subscription points to a channel that was deleted from the database. Instead, log the error and move on so the `list` command is still functional.
**QA Testing**
`/jira subscribe list`
* created subscription to a channel
* verified the webhook sent a notification to the channel
* manually deleted channel from the Database
* `/jira subscribe list` still shows channel subscription
* `make restart-server` to pick up the DB change with channel deleted
* `/jira subscribe list` 
* does not show subscription for the channel
* does not respond with `failed to get channel`
* sends logged message for deleted channel(s)
* ![image](https://user-images.githubusercontent.com/7575921/124163736-7dad6600-da65-11eb-82a1-3992f75ffa17.png)
`Webhook Notifications`
When a channel …
=> [GH-772] - allow `/subscribe list` command to continue if channel has been deleted.

go.mod, go.sum, server/command.go, server/command_test.go, server/utils/utils.go, server/utils/utils_test.go
Signed-off-by: Soner Eker <sonereker@gmail.com>
Before trying to install Jira instance (cloud or server), do a `GET` request to instance `/status`
endpoint which basically provides state information of the Jira instance. If instance is in `RUNNING` state, it means instance is accessible and it's OK to continue with installation.
https://github.com/mattermost/mattermost-plugin-jira/issues/745
https://drive.google.com/file/d/1SDyHiRCy5ryKxCnKU98xvokVH5cD677R/view?usp=sharing
=> [GH-745] Check status of the Jira instance before trying to install

server/client.go, server/issue.go
When JIRA issue has alphanumeric id (like GEN2-3080) it cannot be found when user is trying attach comment from the Mattermost chat to Jira
fixes: https://github.com/mattermost/mattermost-plugin-jira/pull/749
=> Fix for #749 - problem with recognizing Jira issues with alphanumeric issue ID

docs/end-user-guide/interacting-with-forms.md, docs/end-user-guide/using-jira-commands.md
Currently the [Using /jira commands](https://mattermost.gitbook.io/plugin-jira/end-user-guide/using-jira-commands) page has information about using the modals shuffled into the command explanations. This PR separates the two sections into different pages.
=> Separate UI-related end-user docs from commands section

build/custom.mk
Add back build info for `/jira info`. This was broken in https://github.com/mattermost/mattermost-plugin-jira/pull/712.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/806
=> Add back build info

Makefile, webapp/webpack.config.js
For some more context, see [here](https://community.mattermost.com/core/pl/1fkkx7pj1jrwffrc6drh3x71eh). The short version though is that we updated the web app to React 17, and there's a chance that plugins will have some issues with it because they're compiled with the React 16 version of ReactDOM. I'm submitting PRs to the 3 products, the demo plugin, and the plugin template to have them use the web app's version of React DOM to fix any immediate issues, but we'll want to properly migrate them to React 17 going forward.
https://mattermost.atlassian.net/browse/MM-47046
- https://github.com/mattermost/mattermost-plugin-playbooks/pull/1489
- https://github.com/mattermost/focalboard/pull/3861
- https://github.com/mattermost/mattermost-plugin-demo/pull/153
- …
=> MM-47046/MM-47052 Use version of React DOM provided by web app

docs/setup/configuration.md, server/command.go
Adding /setup to autocomplete
https://github.com/mattermost/mattermost-plugin-jira/issues/892
=> Adding /setup to autocomplete (GitHub issue mattermost#892)

webapp/src/components/jira_field.jsx
**Summary** 
- Clicking the x next to an array element in the JIRA create issue modal causes a Javascript error to occur, though clicking the x to the right of the select box works correctly.
**Issue** 
- [Issue #867](https://github.com/mattermost/mattermost-plugin-jira/issues/867)
=> [GH-867]:Clicking the x next to an array element in the JIRA create issue modal causes a Javascript error

webapp/package-lock.json
Moment.js is a JavaScript date library for parsing, validating, manipulating, and formatting dates. A path traversal vulnerability impacts npm (server) users of Moment.js between versions 1.0.1 and 2.29.1, especially if a user-provided locale string is directly used to switch moment locale. This problem is patched in 2.29.2, and the patch can be applied to all affected versions. As a workaround, sanitize the user-provided locale name before passing it to Moment.js.
st is a module for serving static files on web pages, and contains a In our server, we will serve files from the public route.If an attacker requests the following URL from our server, it will in turn leak the sensitive private key of the root user.
```
curl http://localhost:8080/public/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/root/.s …
```
=> Fixed Path Traversal: `dir/../../filename` in moment.locale 

server/plugin.go
There are blocks in the `OnSendDailyTelemetry` function that check for an error, and log the error, but doesn't actually handle the error afterwards. This PR makes it so we don't attempt to access the invalid return value used in the error'd function calls.
https://github.com/mattermost/mattermost-plugin-jira/blob/e4f60983998d0f474172df79f76b5d9b087e3838/server/plugin.go#L519-L531
=> Improve error handling in `OnSendDailyTelemetry`

server/atlassian_connect.go, server/autocomplete_search.go, server/command.go, server/http.go, server/http_test.go, server/info.go, server/instances.go, server/issue.go, server/issue_parser.go, server/issue_test.go, server/plugin.go, server/plugin_test.go, server/setup_flow.go, server/subscribe.go, server/user.go, server/user_cloud.go, server/user_server.go, server/user_test.go, server/webhook.go, server/webhook_http.go, server/webhook_http_test.go
Migrate JIRA codebase to use mux.Router
https://mattermost.atlassian.net/browse/MM-51188
=> MM-51188 Use mux.Router

server/utils.go, server/utils_test.go
Fixes #924.
I tested these changes using my personal build of the plugin.
P.S I can also add tests to it if needed.
=> Allow the "@" character when parse jira usernames

readme.md
This PR migrates the Jira plugin documentation https://mattermost.gitbook.io/plugin-jira/ currently hosted via GitBook to the GitHub repository README file.
Once this PR is merged, the GitBook-hosted content can be archived/removed.
=> Migrate Docs from GitBook

readme.md
Specifically, removing "Enterprise Edition" which would imply an unlicensed [Enterprise Edition binary](https://docs.mattermost.com/about/editions-and-offerings.html#mattermost-enterprise-edition) supports multiple Jira instances
=> Clarifying which plans support multiple Jira instances

server/webhook.go, server/webhook_parser.go, server/webhook_worker.go
Unsupported events are not an error and should not be logged as such.
Found while debugging https://community.mattermost.com/core/pl/iu8bucepfpgy5c6xjoqx5m4goa
=> Don't log unsupported webhook events as errors

server/testdata/webhook-cloud-comment-created-mention-user.json, server/testdata/webhook-server-issue-updated-commented-mention-user.json, server/utils.go, server/webhook_http_test.go
**Summary** 
- Fixed the issue that users were not getting DM notifications when they are mentioned in a Jira issue comment.
- Updated the code to replace the jira username or email address with mattermost username.
**Issue** 
- [Issue #954](https://github.com/mattermost/mattermost-plugin-jira/issues/954)
=> [GH-954]:Fixed issue 'DM comment notifications not working'

plugin.json
- https://github.com/mattermost/mattermost-plugin-jira/pull/949
- https://github.com/mattermost/mattermost-plugin-jira/pull/951
- https://github.com/mattermost/mattermost-plugin-jira/pull/961
- https://github.com/mattermost/mattermost-plugin-jira/pull/900
- https://github.com/mattermost/mattermost-plugin-jira/pull/879
- https://github.com/mattermost/mattermost-plugin-jira/pull/821
- https://github.com/mattermost/mattermost-plugin-jira/pull/923
- https://github.com/mattermost/mattermost-plugin-jira/pull/921
- https://github.com/mattermost/mattermost-plugin-jira/pull/925
- https://github.com/mattermost/mattermost-plugin-jira/pull/858
- https://github.com/mattermost/mattermost-plugin-jira/pull/931
- https://github.com/mattermost/mattermost-plugin-jira/pull/916
- …
=> Release 4.0.0

server/plugin.go
This PR fixes a crash occuring when no SiteURL has been configured. Specifically, the PR adds a corresponding check in OnActivate that returns an error and failure.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/974
=> [GH-974] Return error if SiteURL is not set on plugin activation

server/http.go
- Added the endpoint to support the webhooks created for plugin version v2.x.x
#982 
-The webhook created for jira plugin version 2. x.x should be supported and working fine.
- Create a webhook using the readme from https://github.com/mattermost/mattermost-plugin-jira/tree/v2.4.0#step-2-configure-webhooks-in-jira. 
- Create the subscription
- Change notifications should come from the jira side.
=> [GH-982]: Added support for webhook of plugin version v2.x.x

server/command.go, server/instance_cloud_oauth.go, server/instances.go, server/kv.go, server/setup_flow.go, server/webhook_jira.go
- While installing the oauth instance we are storing the previously stored JWT instance data inside the new oauth instance data.
- While getting a client for making the API requests we are returning a JWT client in case the stored JWT instance is not nil and the user's oauth token is nil.
- We have added several debug statements to keep track of how the code is working as there was no way for us to test this change properly. (Since we don't have a server with a JWT (cloud instance) setup)
- If an instance was previously connected to Jira using JWT (cloud instance) and the admin has installed a cloud-oauth instance then all the users who have not connected to oauth yet should be able to continue using the plugin.
- Install a cloud-oauth instance on a server that already has a JWT (cloud …
=> [GH-971] Support Jira migration to Oauth

webapp/src/components/modals/channel_subscriptions/channel_subscriptions_modal.scss, webapp/src/components/modals/channel_subscriptions/select_channel_subscription.tsx
- Fixed the alignment of 'Create Subscription' button on the Jira Subscriptions page.
-  https://github.com/mattermost/mattermost-plugin-jira/issues/957
=> [GH-957]: Fixed issue 'UI for the "Create Subscription" button'

server/autocomplete_search.go, webapp/src/components/data_selectors/jira_autocomplete_selector/jira_autocomplete_selector.tsx, webapp/src/components/data_selectors/jira_user_selector/jira_user_selector.tsx
- Updated the backend code to return proper errors instead of empty responses for the "get-search-autocomplete-fields" and "get-search-users" API.
- Updated UI code to display a generic error in case of "get-search-autocomplete-fields" and "get-search-users" API calls.
Fixes #933
=> [MM-933] Updated code to display proper errors on UI

server/setup_flow.go
- Updated the message in webhookURL modal in the second step of the plugin setup
#939 
- Content of the modal in step 2 of plugin setup(webhook URL step)
- Install the plugin
- run `jira setup`
- open the JIRA bot dm
- Complete Step 1
- Modal to be tested will be visible at the end of step 2
=> [GH-939]: Updated the message for webhookURL in step 2 of plugin setup

.golangci.yml
Fixes: https://github.com/mattermost/mattermost-plugin-jira/actions/runs/7223623524/job/19821776561?pr=976
=> [MM-42] Fix lint error: disabled 'goconst' linter

server/client_cloud.go
Pagination is broken for flows such as the `jira subscribe edit` workflow. Only 50 projects are currently listed, with no way to retrieve additional projects.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/955
=> Fix full fetch logic (resolves #955)

webapp/src/action_types/index.js, webapp/src/actions/index.ts, webapp/src/components/jira_ticket_tooltip/index.ts, webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx, webapp/src/utils/jira_issue_metadata.test.tsx, webapp/src/utils/jira_issue_metadata.tsx
- Added check for undefined fields in ticket data.
- Removed the use of redux in the tooltip component and used local state
The tooltip is rendered properly on hovering on a Jira ticket link in a channel.
1. Connect your Jira account.
2. Hover over any Jira ticket link in a channel.
Fixes #1014 
Fixes #1015
=> [GH-1014,1015] Added check for undefined fields and removed use of redux in tooltip component

webapp/src/components/jira_ticket_tooltip/ticketStyle.scss
- Fix text overflow in the ticket link tooltip description
- Tooltip content is not overflowing in case there is a very long word in the description/title.
1. Connect your Jira account.
2. Create a ticket on Jira with very long words in the description/title.
3. Paste the ticket link in a channel.
4. Hover over the link.
Fixes #1018
=> [GH-1018] Fix text overflow in the ticket link tooltip description

webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx, webapp/src/components/jira_ticket_tooltip/ticketStyle.scss
Removed the project icon from ticket link tooltip
Fixes #1021
=> [GH-1021] Removed the project icon from ticket link tooltip

server/instances.go
**Summary** 
- Added the additional check to remove the instance from the instance array if the key is not present in the KV store.
**Issue** 
- [Issue #902](https://github.com/mattermost/mattermost-plugin-jira/issues/902)
=> [GH-902]:Added check to uninstall server if not found in KV store

server/issue_parser.go, server/issue_parser_test.go
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1032
=> [GH-1032] Fix NPE if reporter is blank during issue creation

server/command.go, server/issue.go, server/subscribe.go, server/user.go, webapp/src/components/jira_instance_and_project_selector/jira_instance_and_project_selector.test.tsx, webapp/src/components/jira_instance_and_project_selector/jira_instance_and_project_selector.tsx, webapp/src/components/modals/attach_comment_modal/attach_comment_form.tsx, webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.test.tsx, webapp/src/components/modals/channel_subscriptions/edit_channel_subscription.tsx, webapp/src/components/modals/create_issue/create_issue_form.tsx, webapp/src/types/model.ts
Updated logic to store the last used issue type value while creating the issue and prefill the modal with those values the next time the user creates an issue.
1. The specified fields are getting pre-filled properly.
2. A new issue is getting created successfully.
3. The prefilled value does not exist on Jira anymore.
Fixes #855
=> [GH-855] Save user's last used field values

server/setup_flow.go
1) Updated the step to include the sharing of the app to make it public and usable to other users in the setup command for cloud Oauth2.0.
https://github.com/mattermost/mattermost-plugin-jira/issues/1007
1) Run the slash command /jira setup and select cloud Oauth2.0. In the step 1: Creation of the App, You can find an additional step to make the app public.
=> [GH-1007]: Updated the instruction in the setup flow for the cloud Oauth2.0

server/command.go
Remove the "cloud" JWT instance type from install, uninstall paths & help text.
Check for JWT/Cloud instance type in any command/autocomplete, i.e. install, uninstall, help etc
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/996
=> [MM-996]: removed jwt instance from setup autocomplete

server/webhook_http.go
- The "updated_priority" event param for legacy webhooks was misspelled as "updated_prioity". We added the correct event param without changing the existing one, so that the functionality of existing users does not get affected.
Documentation update PR: https://github.com/mattermost/docs/pull/7238
- Users are getting notified for priority change event in for both event params i.e. "updated_priority" and "updated_prioity"
- Install a Jira instance on you MM
- Do not connect your account
- Setup a [legacy webhook](https://docs.mattermost.com/integrate/jira-interoperability.html#legacy-jira-webhooks)
- Update the priority of any ticket on Jira
Fixes #1087
=> [GH-1087] Add "updated_priority" event param for legacy webhooks

server/command.go, server/instances.go
Updated the instance connect autocomplete data to show alias and url both
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/673
=> [MM-673]: Updated the instance connect autocomplete data to show alias and url both

server/webhook_parser.go, server/webhook_parser_misc_test.go
- Corrected Markdown formatting for Jira comments received as subscriptions in Mattermost.
- Note that Mattermost does not support colored text in Markdown; any colored text from Jira comments will be displayed as plain text in Mattermost.
**Important:** This PR employs regular expressions to identify and replace various Markdown elements. If these identifiers are present exactly as written in the comment, they will be interpreted as Markdown by Mattermost. However, the likelihood of this occurring is minimal.
- Setup Jira plugin and create a subscription for issue comment/issue description
- Comment on an issue or update the description of a ticket
- Check the markdowns used in Jira and their equivalent markdown on Mattermost
- Bold
- strikethrough
- color
- numbered list
- links
- code …
=> [MM-1096]: Fixed improper markdown for Jira comments received as a subscription in mattermost

server/command.go
Added setup and webhook command to system admin help text
fixes https://github.com/mattermost/mattermost-plugin-jira/issues/987
=> [MM-987]: Added setup and webhook command to system admin help text

Makefile
Fixing failing CI by updating `golangci-lint` version from 1.51.1 to 1.50.0
Refer to this [conversation](https://github.com/github/codeql-action/issues/2581) for more reference
=> Fixing failing CI by updating golangcilint version

webapp/src/actions/index.ts, webapp/src/components/modals/disconnect_modal/disconnect_modal_form.tsx, webapp/src/components/modals/disconnect_modal/index.ts, webapp/src/types/model.ts
Resolved TS errors in action and disconnect modal files
https://github.com/mattermost/mattermost-plugin-jira/pull/1140
- Complete major functionality of the plugin
=> [MM-983]: Resolved TS errors in action and disconnect modal files

plugin.json, server/issue.go, server/kv_mock_test.go, server/plugin.go, server/plugin_test.go, server/utils.go
- Added support for CloudOAuth for Autolink
- Updated the API call to get Issues with AdminAPIToken
- Added test cases for the SetupAutoLink function
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1137
- Autolink for Jira tickets
- Issue comment notification after the admin has disconnected his Jira account
- Keep an eye on the server logs
- Install autolink plugin for you MM
- Install Jira plugin
- Add the admin API token and admin email in the Jira plugin configuration before enabling it
- enable the plugin
- Paste a link to a jira ticket on your MM chat
=> [MM-1137]: Added Autolink support for cloud-oauth

plugin.json, webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
This fix backports the fix for improved link tooltip to work with version prior to MM v10.5 as well. The minimum MM version for plugin is also reverted back to v7.8. Changes adds more lifecycle hooks one for 10.5 and other for less than that.
Fixes https://mattermost.atlassian.net/browse/MM-62634
With v10.5
With less than v10.5
=> [MM-62634] Change the fix for LinkTooltip to be backward compatible for jira plugin

server/webhook_parser.go, server/webhook_parser_misc_test.go
Fixed the issue of code block rendering in the subscription post
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1154
=> [MM-1064]: Fixed issue of code block rendering in subscription post

server/issue_parser.go
Handled the truncation of the issue summary while making it a link for the message
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1108
- Connect your JIra to mattermost
- Subscribe to Jira project
- Create a Jira issue with in the same project with a very long summary
- Check the subscription post in mattermost
=> [MM-1108]: Handled the truncation of issue summary while making it a link for message

server/webhook_parser.go, server/webhook_parser_misc_test.go
Fix multi-line code block rendering in the Jira subscription post
- Create a subscription for JIra
- Comment on the Jira issue with multi-line code block with and without specifying language
=> Fix multi line code block rendering in Jira subscription post

server/plugin.go
Fixed the issue of config not prefilling when uploading a new build of release 4.2.0
- Upload release 4.1.1 build
- Generate and set all plugin config
- Create & test webhook
- Upload new build
- Bool and string configs should be prefilled to the previous configs and webhooks should remain working
=> fixed issue of plugin config not prefilling from previous build

server/webhook.go, server/webhook_worker.go
- Fixed the issue of receiving the Jira subscription after the channel is archived
- Create a subscription in a channel and check if the subscription is working
- Archive the channel
- Try sending more subscription events
- Unarchive the channel
- Subscription event notifications are received after the channel is archived
- No subscription event notification received after the channel is archived
Fixes #571
=> [MM-571]: Fixed the issue of receiving Jira subscription after the channel is archived

webapp/src/components/data_selectors/jira_epic_selector/jira_epic_selector.tsx
- The `Create Issue` modal had a bug: if the `Epic` field in a Jira project was renamed to anything other than `Epic`, the dropdown for selecting Jira epics displayed no options.
- The existing logic iterates over each field in the Jira project, filtering for fields named `Epic`, and then checks if the filtered field matches the Epic field schema before fetching all epics from the project.
- The bug occurred because the code depended solely on finding a field named `Epic`. This PR removes the name-based check and instead relies exclusively on the field schema to identify the Epic field.
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1121
- Create different fields of [epic](https://community.atlassian.com/t5/Jira-questions/How-do-I-create-an-Epic-on-a-JIRA-software-projec …
=> [MM-1121]: Fix epic selector not displaying options if field is renamed in Jira

webapp/src/actions/index.ts
Issue #768 remains relevant. The previous PR #870 introduced a new `baseUrl` variable intended to resolve a bug where the `/jira connect` command did not include the subpath in the URL when Mattermost was running on a subpath. However, this variable was never utilized, and as a result, the issue persisted. Furthermore, the `baseUrl` variable was removed in a later commit while addressing linting errors [a206519](https://github.com/mattermost/mattermost-plugin-jira/commit/a206519f9ad88e55a5ad7a1aabc8d29d0b68dc23#diff-3890cc5337cb185259d5838427a78eb3a949f1efbacdcdacea1479d719e101c9L436).
This PR reintroduces the `baseUrl` variable and ensures it is properly utilized, effectively resolving the bug.
Fixes PR #870
Fixes issue #768
=> [GH-768] Fix redirect connect doesn't open mattermost's subpath url

server/instance_server.go
Updated error message to use Name instead of Display name
https://github.com/mattermost/mattermost-plugin-jira/issues/1023#issuecomment-1906726933
=> [MM-178] Updated error message to use Name instead of Display name
